#!/bin/bash

#	Copyright (C) 2011  Unison Networks Ltd
#
#	This program is free software: you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation, either version 3 of the License, or
#	(at your option) any later version.
#
#	This program is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with this program.  If not, see <http://www.gnu.org/licenses/>.

# For the moment, we just print out a message to the user.
echo -e "${BOLD_CYAN}Target specific configuration...\n${NO_COLOUR}"

# Create a separate section in the component configuration file for target specific stuff.
echo -e "### TARGET SPECIFIC ###\n" >> $TCPATH/src/$COMPONENT/$COMPONENT_NAME.cfg

# Ask if the user wants to include the standard startup code file (taken from the Luminary Micro Peripheral Driver Library).
echo -e -n "${GREEN}Do you wish to use standard startup code (else you must create your own)? (Y/N) ${NO_COLOUR}"
read -n 1
echo -e "\n" # NOTE - This is because the read command won't put a newline after it reads a character.
		
# If they responded YES, then add the startup code to the list of files to import.  If NO, then move on.
if [[ $REPLY =~ ^[Yy]$ ]]; then
	# Add the startup files to the list of files to import.
	echo -e "SRC_IMPORT_FILES+=' res/arm/embedded-arm/lm3s1968/startup.c:startup.c'" >> $TCPATH/src/$COMPONENT/$COMPONENT_NAME.cfg
	echo -e "SRC_IMPORT_FILES+=' res/arm/embedded-arm/lm3s1968/startup.h:startup.h'" >> $TCPATH/src/$COMPONENT/$COMPONENT_NAME.cfg
fi

# Write any other configuration entries, then a blank line, to the configuration file.
echo -e "" >> $TCPATH/src/$COMPONENT/$COMPONENT_NAME.cfg

# All done.

