#!/usr/bin/env bash

#	Copyright (C) 2011 Unison Networks Ltd
#
#	This program is free software: you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation, either version 3 of the License, or
#	(at your option) any later version.
#
#	This program is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with this program.  If not, see <http://www.gnu.org/licenses/>

###########################################################################################################################
###
### Name:		resettc
###
### Author:		Zac Frank
###
### Date Created:	17-11-2011
###
### Type:		Bash Script
###
### Purpose:    Resets the toolchain to its default condition.  Note that this doesn't touch the contents of	###
###			the src or lib folder if they are not empty.
###
###########################################################################################################################

# MAKE SURE WE'RE IN A SANE ENVIRONMENT.

# Determine which operating system we are using.
VF_OS="$(uname)"
unset VF_OS_DARWIN
unset VF_OS_LINUX
if [ "${VF_OS}" == "Darwin" ]; then
	VF_OS_DARWIN=1
	VF_OSCFG_READLINK='greadlink'
	VF_OSCFG_SED='gsed'
	VF_OSCFG_SED_EXTPARAM='-E'
	VF_OSCFG_SED_INLPARAM='-i'
else
	VF_OS_LINUX=1
	VF_OSCFG_READLINK='readlink'
	VF_OSCFG_SED='sed'
	VF_OSCFG_SED_EXTPARAM='-r'
	VF_OSCFG_SED_INLPARAM='-i'
fi

# Check if we've got a sufficiently advanced version of BASH to actually run the toolchain.
if [[ ${BASH_VERSINFO[0]} < 4 ]]; then
	# BASH version before v4 are missing things we required, such as "read -i".
	echo -e "\033[0;31mBASH versions prior to 4.x are not supported.  Upgrade to a never version of BASH."
	exit 1
fi

# Check if all the tools we're expecting are installed.
VF_REQUIRED="${VF_OSCFG_READLINK} ${VF_OSCFG_SED}"
for VF_REQUIRED_ITEM in ${VF_REQUIRED}; do
	if [ -z "$(which ${VF_REQUIRED})" ]; then
		echo -e "\033[0;31mUnabled to find: ${VF_REQUIRED}.  Install this utility then try again."
		exit 1
	fi
done
unset VF_REQUIRED_ITEM
unset VF_REQUIRED

# Determine what the absolute path to the root of the toolchain is.
VF_SCRIPTPATH=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
TCPATH=$(echo $VF_SCRIPTPATH | ${VF_OSCFG_SED} 's/\/bld.*//')

# DEFINE CONSTANTS.

# Define file names.

DEFAULT_USER_CONFIG_FILE="bld/default_user_config.cfg"
USER_CONFIG_FILE="var/config.cfg"

# Define the colours used for interface output.
source $TCPATH/bld/common/def_colours

# Define the functions used for set up the compilers.
source $TCPATH/bld/other/setup_compilers

# Create directories which don't come automatically with the toolchain.
source $TCPATH/bld/common/create_empty_dirs

################################ SCRIPT PROPER STARTS HERE ###############################

# Make sure we can find the default user configuration file.
if [ -r $TCPATH/$DEFAULT_USER_CONFIG_FILE ]; then
	# Set the user configuration back to the defaults.
	echo -e "${BOLD_CYAN}Reverting user configuration to defaults...\n${NO_COLOUR}"
	cp $TCPATH/$DEFAULT_USER_CONFIG_FILE $TCPATH/$USER_CONFIG_FILE
else
	# Something is terribly, terribly wrong.
	echo -e "${BOLD_RED}FATAL - Default user configuration file not found.\n${NO_COLOUR}"
	exit 1
fi

# Pack all the compilers up.
echo -e "${BOLD_CYAN}Packing up compilers...\n${NO_COLOUR}"
pack_allc

# Delete all the folders the toolchain creates (except src and lib, if they have anything in them).
echo -e "${BOLD_CYAN}Removing directories...\n${NO_COLOUR}"

# Remove the tmp folder.
rm -Rf ${TCPATH}/tmp

# Remove the bin folder.
rm -Rf ${TCPATH}/bin

# Remove the res/arm/omap4/images folder.
rm -Rf ${TCPATH}/res/arm/omap4/images

# Remove the res/arm/omap4/ubuntu/images folder.
rm -Rf ${TCPATH}/res/arm/omap4/ubuntu/images

# Remove the src folder only if it empty.
rmdir ${TCPATH}/src 2> /dev/null

# Remove the lib folder only if it empty.
rmdir ${TCPATH}/lib 2> /dev/null

# Indicate that we're done.
echo -e "${BOLD_CYAN}All done.\n${NO_COLOUR}"

# All done.
exit 0


