#!/usr/bin/env bash

#	Copyright (C) 2012 Unison Networks Ltd
#
#	This program is free software: you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation, either version 3 of the License, or
#	(at your option) any later version.
#
#	This program is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with this program.  If not, see <http://www.gnu.org/licenses/>

###########################################################################################################################
###															###
### Name:		make_arduino											###
###															###
### Author:		Edwin Hayes											###
###															###
### Date Created:	19-03-2012											###
###															###
### Type:		Bash Script											###
###															###
### Purpose:		Provides functions which makes Arduino type components.						###
###															###
###########################################################################################################################

# Indicate the file was imported successfully.
echo -e "${CYAN}Imported Arduino make-functions.\n${NO_COLOUR}"

# Select the source files for the AWK scripts we use.
ARDUINO_AWK_SPLITTER="${TCPATH}/bld/make_functions/avr/awk_makearduino_splitter"
ARDUINO_AWK_PROTOTYPER="${TCPATH}/bld/make_functions/avr/awk_makearduino_prototyper"

######################################## FUNCTION #########################################
###											###
### Name:		makearduino							###
###											###
### Inputs/Outputs:	None								###
###											###
### Purpose:		Prepares Arduino source files in the tmp directory, then copies	###
###			the Arduino makefile into tmp directory, edits it, and uses it	###
###			to compile the files.				     		###
###											###
###########################################################################################

makearduino()
{
	# Perform the standard precompile routine.
	if ! generic_precompile; then
		# There isn't anything to do.
		echo -e "${YELLOW}Nothing to make for component $COMPONENT.\n${NO_COLOUR}"
		return 1
	fi

	# Set up the Arduino compiler.
	unpack_arduinoc

	# NOTE - Arduino targets only support a single application executable, so it is named the same as the component.

	# NOTE - However, we also allow the user to name a specific sketch file, in case they are forced to compile non-compliant code.

	# Because Arduino builds are different to regular ValleyForge C/C++ builds, we need to do some configuration of the source files first.
	echo -e "${CYAN}Configuring Arduino source files...\n${NO_COLOUR}"
	
	pushd $TCPATH/$TMP_SRC_DIR/$COMPONENT >/dev/null
	# Check if a specific sketch to build was specified for the component.
	if [ -z "${ARDUINO_SKETCH}" ]; then
		# No sketch was specified, so assume it's named after the component.
		if [ -e ${COMPONENT_NAME}.ino ]; then
			ARDUINO_SKETCH="${COMPONENT_NAME}.ino"
		elif [ -e ${COMPONENT_NAME}.c ]; then
			mv ${COMPONENT_NAME}.c ${COMPONENT_NAME}.ino
			ARDUINO_SKETCH="${COMPONENT_NAME}.ino"
		elif [ -e ${COMPONENT_NAME}.cpp ]; then
			mv ${COMPONENT_NAME}.cpp ${COMPONENT_NAME}.ino
			ARDUINO_SKETCH="${COMPONENT_NAME}.ino"
		fi
	fi
	popd >/dev/null

	# We need to handle non-compliant nesting (since Arduino projects don't play nicely with ValleyForge) where the parent file isn't in the root.
	ARDUINO_BUILD_DIR=$TCPATH/$TMP_SRC_DIR/$COMPONENT/${ARDUINO_SKETCH}
	ARDUINO_BUILD_DIR=${ARDUINO_BUILD_DIR%/*}
	# Check if the sketch file we have decided to build actually exists.
	if [ ! -f "${ARDUINO_BUILD_DIR}/${ARDUINO_SKETCH##*/}" ]; then
		# The sketch file doesn't exist, so we have to abort.
		echo -e "${RED}The specified sketch file (${ARDUINO_SKETCH}) does not exist.  Failed to build component $COMPONENT.\n${NO_COLOUR}"
		return 1
	fi

	# We convert the Arduino PDE/INO file format into a real CPP file which can be compiled.

	# NOTE - LC_ALL needs to be exported to 'C' to get case-sensitive sorting, which is important since stupidly the Ardupilot code depends upon it.

	# List the sketch source files (PDE/INO) other than the parent.
	export LC_ALL=C
	ARDUINO_PDE_FILES=`find "$ARDUINO_BUILD_DIR" -maxdepth 1 -not -name "${ARDUINO_SKETCH##*/}" -name "*.pde" -o -not -name "${ARDUINO_SKETCH##*/}" -name "*.ino" | sort`
	export LC_ALL=

	# NOTE - The actual conversion logic is performed via a set of AWK scripts, which are stored as separate files.

	# Our AWK scripts will go horribly wrong if there are DOS line endings, so we make sure there aren't any.
	dos2unix "${ARDUINO_BUILD_DIR}/${ARDUINO_SKETCH##*/}" >/dev/null 2>&1
	for FILE in ${ARDUINO_PDE_FILES}; do
		dos2unix $FILE >/dev/null 2>&1 
	done

	# Convert the PDE/INO's to a CPP by adding function prototypes and merging them all together.
	echo -e "${CYAN}\tConverting PDE/INO files into a CPP file...\n${NO_COLOUR}"
	ARDUINO_CPP_FILE="${ARDUINO_SKETCH%.*}.cpp"
	awk -v mode=header -f "${ARDUINO_AWK_SPLITTER}" "${ARDUINO_BUILD_DIR}/${ARDUINO_SKETCH##*/}" ${ARDUINO_PDE_FILES} > "$TCPATH/$TMP_SRC_DIR/$COMPONENT/${ARDUINO_CPP_FILE}"
	echo "#line 1 \"autogenerated\"" >> "$TCPATH/$TMP_SRC_DIR/$COMPONENT/${ARDUINO_CPP_FILE}"
	awk -f ${ARDUINO_AWK_PROTOTYPER} "${ARDUINO_BUILD_DIR}/${ARDUINO_SKETCH##*/}" ${ARDUINO_PDE_FILES} >> "$TCPATH/$TMP_SRC_DIR/$COMPONENT/${ARDUINO_CPP_FILE}"
	awk -v mode=body -f ${ARDUINO_AWK_SPLITTER} "${ARDUINO_BUILD_DIR}/${ARDUINO_SKETCH##*/}" ${ARDUINO_PDE_FILES} >> "$TCPATH/$TMP_SRC_DIR/$COMPONENT/${ARDUINO_CPP_FILE}"
	# Then remove the PDE/INO files.
	rm ${ARDUINO_PDE_FILES} $TCPATH/$TMP_SRC_DIR/$COMPONENT/${ARDUINO_SKETCH}

	# Since our usual dependency detection can't detect them, make a list of all the user libraries we expect to use.

	# NOTE - The reason for this is that Ardupilot et al will include "library.h" instead of "lib_dir/library/library.h" as we expect.

	# Only create a user library listing if we specified a library directory to use.
	if [ -n "${ARDUINO_LIB_DIR}" ]; then
		# Check if the specified library directory actually exists.
		if [ -d "$TCPATH/$TMP_SRC_DIR/$COMPONENT/${ARDUINO_LIB_DIR}" ]; then
			# List all of the library directories we want to include.
			echo -e "${CYAN}\tDetecting user library dependencies (${ARDUINO_LIB_DIR})...\n${NO_COLOUR}"
			echo -n -e "${NO_COLOUR}\t\t"

			# We do something which approximates dependency detection here.

#			# Get a list of all the imports from the CPP file.
#			ARDUINO_IMPORTS=`cat "$TCPATH/$TMP_SRC_DIR/$COMPONENT/${ARDUINO_CPP_FILE}" | grep -E '^#include\\s+(\\"|<)(\\w|\\.|/)+\\.h(\\"|>)' | ${VF_OSCFG_SED} ${VF_OSCFG_SED_EXTPARAM} 's^#include\\s+(\\"|<)^^g' | ${VF_OSCFG_SED} ${VF_OSCFG_SED_EXTPARAM} 's^(\\"|>).*$^^'`
		
			ARDUINO_USER_LIBRARIES=
			list_user_import_recursive()
			{
				# Iterate over each of the files we were just told to recurse into.
				for FILE in $*; do
					# If the file we're recursing into doesn't exist, we just do nothing.
					if [ ! -f "$FILE" ]; then
						continue
					fi

					local ARDUINO_IMPORTS=`cat "$FILE" | grep -E '^#include\\s+(\\"|<)(\\w|\\.|/)+\\.h(\\"|>)' | ${VF_OSCFG_SED} ${VF_OSCFG_SED_EXTPARAM} 's^#include\\s+(\\"|<)^^g' | ${VF_OSCFG_SED} ${VF_OSCFG_SED_EXTPARAM} 's^(\\"|>).*$^^'`

					# Iterate over each of the imported header files.
					for HEADER_FILE in ${ARDUINO_IMPORTS}; do
						# Check if this header file is somewhere in the user libraries folder.
						local USER_LIBRARY=`find "$TCPATH/$TMP_SRC_DIR/$COMPONENT/${ARDUINO_LIB_DIR}" -wholename "*/${HEADER_FILE}" | head -1`
						USER_LIBRARY="${USER_LIBRARY///${HEADER_FILE}}" # Cut the header file name off.
						USER_LIBRARY_ROOT="$TCPATH/$TMP_SRC_DIR/$COMPONENT/${ARDUINO_LIB_DIR}/"
						USER_LIBRARY="${USER_LIBRARY/${USER_LIBRARY_ROOT}}" # Cut the root library path off.

						# Check if we actually found a matching library.
						if [ -z "${USER_LIBRARY}" ]; then
							# We didn't find a matching library, so just move on.
							continue
						fi

						# Check if the library is already in the list of libraries.
						if [ -n "`echo ${ARDUINO_USER_LIBRARIES} | grep \"\b${USER_LIBRARY}\b\"`" ]; then
							# The library is already in the list, so just move on.
							continue
						fi

						# Add the folder containing this header to the list of user libraries.
						ARDUINO_USER_LIBRARIES+="${USER_LIBRARY} "
						echo -n "${USER_LIBRARY} "

						# Recurse into anything in this directory which might import anything else we'll need.
						list_user_import_recursive $TCPATH/$TMP_SRC_DIR/$COMPONENT/${ARDUINO_LIB_DIR}/${USER_LIBRARY}/*.hpp
						list_user_import_recursive $TCPATH/$TMP_SRC_DIR/$COMPONENT/${ARDUINO_LIB_DIR}/${USER_LIBRARY}/*.h
						list_user_import_recursive $TCPATH/$TMP_SRC_DIR/$COMPONENT/${ARDUINO_LIB_DIR}/${USER_LIBRARY}/*.cpp
						list_user_import_recursive $TCPATH/$TMP_SRC_DIR/$COMPONENT/${ARDUINO_LIB_DIR}/${USER_LIBRARY}/*.c
					done
				done
			}


			# Obviously, search the main CPP file for user library requirements.
			list_user_import_recursive "$TCPATH/$TMP_SRC_DIR/$COMPONENT/${ARDUINO_CPP_FILE}"
			# But also, any loose objects which will be compiled separately.
			for LOOSE_OBJECT in ${LOOSE_OBJECTS}; do
				list_user_import_recursive $TCPATH/$TMP_SRC_DIR/$COMPONENT/${LOOSE_OBJECT%.*}.cpp
				list_user_import_recursive $TCPATH/$TMP_SRC_DIR/$COMPONENT/${LOOSE_OBJECT%.*}.c
			done

			# Check if we actually found any dependencies.
			if [ -n "${ARDUINO_USER_LIBRARIES}" ]; then
				echo -e "\n"
			else
				echo -e "${YELLOW}No user library dependencies detected.\n${NO_COLOUR}"
			fi
		else
			# It seems a bit strange the specified library directory didn't exist.
			echo -e "${YELLOW}\tThe specified Arduino user library directory (${ARDUINO_LIB_DIR}) didn't exist.\n${NO_COLOUR}"
			ARDUINO_USER_LIBRARIES=
		fi
	else
		# Indicate there was no library directory specified.
		echo -e "${CYAN}\tNo Arduino user library directory specified.\n${NO_COLOUR}"
		ARDUINO_USER_LIBRARIES=
	fi

	# If we are using a specific Arduino 'core', then we'll need to include this instead of the regular Arduino core files.

	# TODO - The default paths need to be calculated depending on the type of Arduino.

	# By default, we use the regular Arduino core (and associated Arduino libraries).
	if [ -z "${ARDUINO_VARIANT}" ]; then
		# No variant has been selected.
		echo -e "${RED}\tNo Arduino variant selected in configuration.\n${NO_COLOUR}"
		return 1
	fi
	ARDUINO_VARI_PATH=
	if [ -n "${ARDUINO_VARI_DIR}" ]; then
		# Specify the path to the core variants directory.
		ARDUINO_VARI_PATH="${ARDUINO_VARI_DIR}"
	else
		# Specify the default core variants directory.
		ARDUINO_VARI_PATH="$TCPATH/tmp/tmp_compiler/arduino/arduino-dist/hardware/arduino/avr/variants"
		mkdir -p "$TCPATH/$TMP_SRC_DIR/$COMPONENT/arduino_core/variants"
		cp -rf ${ARDUINO_VARI_PATH} "$TCPATH/$TMP_SRC_DIR/$COMPONENT/arduino_core"
		ARDUINO_VARI_PATH="arduino_core/variants"
	fi
	ARDUINO_CORE_PATH=
	if [ -n "${ARDUINO_CORE_DIR}" ]; then
		# Specify the path to the core directory.
		ARDUINO_CORE_PATH="${ARDUINO_CORE_DIR}"
	else
		# Specify the default core directory.
		ARDUINO_CORE_PATH="$TCPATH/tmp/tmp_compiler/arduino/arduino-dist/hardware/arduino/avr/cores/arduino"
		mkdir -p "$TCPATH/$TMP_SRC_DIR/$COMPONENT/arduino_core/arduino"
		cp -rf ${ARDUINO_CORE_PATH} "$TCPATH/$TMP_SRC_DIR/$COMPONENT/arduino_core"
		ARDUINO_CORE_PATH="arduino_core/arduino"
	fi

	# NOTE - Now there are AVR and ARM Arduinos, there are two core library locations, one for common stuff, the other hardware specific.

	ARDUINO_CORELIB_PATH=
	if [ -n "${ARDUINO_CORELIB_DIR}" ]; then
		# Specify the path to the core libraries directory.
		ARDUINO_CORELIB_PATH="$TCPATH/$TMP_SRC_DIR/$COMPONENT/${ARDUINO_CORELIB_DIR}"
	else
		# Specify the default core libraries directory.
		ARDUINO_CORELIB_PATH="$TCPATH/tmp/tmp_compiler/arduino/arduino-dist/libraries"
	fi
	ARDUINO_COREHWLIB_PATH=
	if [ -n "${ARDUINO_COREHWLIB_PATH}" ]; then
		# Specify the path to the core HW dependent libraries directory.
		ARDUINO_COREHWLIB_PATH="$TCPATH/$TMP_SRC_DIR/$COMPONENT/${ARDUINO_CORELIB_DIR}"
	else
		# Specify the default core HW depedent libraries directory (we assume AVR).
		ARDUINO_COREHWLIB_PATH="$TCPATH/tmp/tmp_compiler/arduino/arduino-dist/hardware/arduino/avr/libraries"
	fi

	# Since the common Makefile can't detect them, make a list of all the core libraries we expect to use.

	# Only create a core library listing if we specified a library directory to use.
	if [ -n "${ARDUINO_CORELIB_PATH}" ] && [ -n "${ARDUINO_COREHWLIB_PATH}" ]; then
		# Check if the specified library directory actually exists.
		if [ -d "${ARDUINO_CORELIB_PATH}" ] && [ -d "${ARDUINO_COREHWLIB_PATH}" ]; then
			# List all of the library directories we want to include.
			echo -e "${CYAN}\tDetecting core library dependencies...\n${NO_COLOUR}"
			echo -n -e "${NO_COLOUR}\t\t"

			# We do something which approximates dependency detection here.

			ARDUINO_CORE_LIBRARIES=
			list_core_import_recursive()
			{
				# Iterate over each of the files we were just told to recurse into.
				for FILE in $*; do
					# If the file we're recursing into doesn't exist, we just do nothing.
					if [ ! -f "$FILE" ]; then
						continue
					fi	

					local ARDUINO_IMPORTS=`cat "$FILE" | grep -E '^#include\\s+(\\"|<)(\\w|\\.|/)+\\.h(\\"|>)' | ${VF_OSCFG_SED} ${VF_OSCFG_SED_EXTPARAM} 's^#include\\s+(\\"|<)^^g' | ${VF_OSCFG_SED} ${VF_OSCFG_SED_EXTPARAM} 's^(\\"|>).*$^^'`

					# Iterate over each of the imported header files.
					for HEADER_FILE in ${ARDUINO_IMPORTS}; do
						# Check if this header file is somewhere in the core libraries folder.
						local CORE_LIBRARY=`find "${ARDUINO_CORELIB_PATH}" "${ARDUINO_COREHWLIB_PATH}" -wholename "*/${HEADER_FILE}" | head -1`
						CORE_LIBRARY="${CORE_LIBRARY///${HEADER_FILE}}" # Cut the header file name off.

						# Check if we actually found a matching library.
						if [ -z "${CORE_LIBRARY}" ]; then
							# We didn't find a matching library, so just move on.
							continue
						fi

						# Check if the library is already in the list of libraries.
						if [ -n "`echo ${ARDUINO_CORE_LIBRARIES} | grep \"${CORE_LIBRARY}\"`" ]; then
							# The library is already in the list, so just move on.
							continue
						fi

						# Add the folder containing this header to the list of core libraries.
						ARDUINO_CORE_LIBRARIES+="${CORE_LIBRARY} "
						echo -n "${CORE_LIBRARY##*/} "

						# Recurse into anything in this directory which might import anything else we'll need.
						list_core_import_recursive ${CORE_LIBRARY}/*.hpp
						list_core_import_recursive ${CORE_LIBRARY}/*.h
						list_core_import_recursive ${CORE_LIBRARY}/*.cpp
						list_core_import_recursive ${CORE_LIBRARY}/*.c
					done
				done
			}

			# Obviously, search the main CPP file for user library requirements.
			list_core_import_recursive "$TCPATH/$TMP_SRC_DIR/$COMPONENT/${ARDUINO_CPP_FILE}"
			# But also, any loose objects which will be compiled separately.
			for LOOSE_OBJECT in ${LOOSE_OBJECTS}; do
				list_core_import_recursive $TCPATH/$TMP_SRC_DIR/$COMPONENT/${LOOSE_OBJECT%.*}.cpp
				list_core_import_recursive $TCPATH/$TMP_SRC_DIR/$COMPONENT/${LOOSE_OBJECT%.*}.c
			done

			# Check if we actually found any dependencies, and if so, list them.
			if [ -n "${ARDUINO_CORE_LIBRARIES}" ]; then
				echo -e "\n"
			else
				echo -e "${YELLOW}No core library dependencies detected.\n${NO_COLOUR}"
			fi
		else
			# It seems a bit strange the specified library directory didn't exist.
			echo -e "${YELLOW}\tThe specified Arduino core library directory (${ARDUINO_CORELIB_DIR}) didn't exist.\n${NO_COLOUR}"
			ARDUINO_CORE_LIBRARIES=
		fi
	else
		# Indicate there was no library directory specified, which shouldn't every happen.
		echo -e "${RED}\tNo Arduino core library directory specified.  This is probably a bug.\n${NO_COLOUR}"
		ARDUINO_CORE_LIBRARIES=
	fi

	# Since we will actually need to compile the core libraries, we'll need to copy the required ones in with the component.
	mkdir "$TCPATH/$TMP_SRC_DIR/$COMPONENT/arduino_core_libs"
	for CORE_LIBRARY in ${ARDUINO_CORE_LIBRARIES}; do
		# Copy the library folder across.
		cp -rf ${CORE_LIBRARY} $TCPATH/$TMP_SRC_DIR/$COMPONENT/arduino_core_libs/${CORE_LIBRARY##*/}
	done

	# Now, work out exactly what we will need to have as our include path.

	# Iterate over each user library.
	ARDUINO_INCLUDE_LIST="-I ${ARDUINO_BUILD_DIR} "
	for USER_LIBRARY in ${ARDUINO_USER_LIBRARIES}; do
		# Make a list of directories to include.
		ARDUINO_INCLUDE_LIST+="-I ${ARDUINO_LIB_DIR}/${USER_LIBRARY} "
	done
	# Iterate over each core library.
	for CORE_LIBRARY in $(find "$TCPATH/$TMP_SRC_DIR/$COMPONENT/arduino_core_libs" -type d); do
		# Make a list of directories to include.
		ARDUINO_INCLUDE_LIST+="-I arduino_core_libs${CORE_LIBRARY##*arduino_core_libs} "
	done
	# Add the Arduino core directories we selected.
	ARDUINO_INCLUDE_LIST+="-I ${ARDUINO_CORE_PATH} -I ${ARDUINO_VARI_PATH}/${ARDUINO_VARIANT} "

	# Because Arduino components often don't comply with out dependency requirements, we need to add a bunch of libraries onto the include path.
	CFLAGS="${CFLAGS} ${ARDUINO_INCLUDE_LIST}"
	PFLAGS="${PFLAGS} ${ARDUINO_INCLUDE_LIST}"

	# Update the flags in case they still contain some unevaluated variables.
	CFLAGS=$(eval echo $CFLAGS)
	PFLAGS=$(eval echo $PFLAGS)
	AFLAGS=$(eval echo $AFLAGS)
	LFLAGS=$(eval echo $LFLAGS)

	# Arduino targets only support a single application executable, defined by the CPP we created.
	EXECUTABLE=${ARDUINO_CPP_FILE%.*}

	# Copy the relevant makefile in with the source.
	echo -e "${CYAN}Constructing makefile for component $COMPONENT...\n${NO_COLOUR}"
	cp -f $MAKEFILE "$TCPATH/$TMP_SRC_DIR/$COMPONENT/Makefile"

	# Update the working makefile with the appropriate values for this component.
	${VF_OSCFG_SED} ${VF_OSCFG_SED_EXTPARAM} ${VF_OSCFG_SED_INLPARAM} "s^(CC *= *)BUILD_INSERTS_C_COMPILER_HERE(\\s.*)?^\1$C_COMPILER\2^" "$TCPATH/$TMP_SRC_DIR/$COMPONENT/Makefile"
	${VF_OSCFG_SED} ${VF_OSCFG_SED_EXTPARAM} ${VF_OSCFG_SED_INLPARAM} "s^(PC *= *)BUILD_INSERTS_P_COMPILER_HERE(\\s.*)?^\1$P_COMPILER\2^" "$TCPATH/$TMP_SRC_DIR/$COMPONENT/Makefile"
	${VF_OSCFG_SED} ${VF_OSCFG_SED_EXTPARAM} ${VF_OSCFG_SED_INLPARAM} "s^(AS *= *)BUILD_INSERTS_ASSEMBLER_HERE(\\s.*)?^\1$ASSEMBLER\2^" "$TCPATH/$TMP_SRC_DIR/$COMPONENT/Makefile"
	${VF_OSCFG_SED} ${VF_OSCFG_SED_EXTPARAM} ${VF_OSCFG_SED_INLPARAM} "s^(LD *= *)BUILD_INSERTS_LINKER_HERE(\\s.*)?^\1$LINKER\2^" "$TCPATH/$TMP_SRC_DIR/$COMPONENT/Makefile"
	${VF_OSCFG_SED} ${VF_OSCFG_SED_EXTPARAM} ${VF_OSCFG_SED_INLPARAM} "s^(OBJCOPY *= *)BUILD_INSERTS_OBJCOPY_HERE(\\s.*)?^\1$OBJCOPY\2^" "$TCPATH/$TMP_SRC_DIR/$COMPONENT/Makefile"
	${VF_OSCFG_SED} ${VF_OSCFG_SED_EXTPARAM} ${VF_OSCFG_SED_INLPARAM} "s^(OBJDUMP *= *)BUILD_INSERTS_OBJDUMP_HERE(\\s.*)?^\1$OBJDUMP\2^" "$TCPATH/$TMP_SRC_DIR/$COMPONENT/Makefile"
	${VF_OSCFG_SED} ${VF_OSCFG_SED_EXTPARAM} ${VF_OSCFG_SED_INLPARAM} "s^(COMPONENT *= *)BUILD_INSERTS_COMPONENT_HERE(\\s.*)?^\1${COMPONENT_NAME}\2^" "$TCPATH/$TMP_SRC_DIR/$COMPONENT/Makefile"
	${VF_OSCFG_SED} ${VF_OSCFG_SED_EXTPARAM} ${VF_OSCFG_SED_INLPARAM} "s^(EXECUTABLE *= *)BUILD_INSERTS_EXECUTABLE_HERE(\\s.*)?^\1${ARDUINO_SKETCH%.*}\2^" "$TCPATH/$TMP_SRC_DIR/$COMPONENT/Makefile"
	${VF_OSCFG_SED} ${VF_OSCFG_SED_EXTPARAM} ${VF_OSCFG_SED_INLPARAM} "s^(CFLAGS *= *.* *)BUILD_INSERTS_CFLAGS_HERE(\\s.*)?^\1$CFLAGS\2^" "$TCPATH/$TMP_SRC_DIR/$COMPONENT/Makefile"
	${VF_OSCFG_SED} ${VF_OSCFG_SED_EXTPARAM} ${VF_OSCFG_SED_INLPARAM} "s^(PFLAGS *= *.* *)BUILD_INSERTS_PFLAGS_HERE(\\s.*)?^\1$PFLAGS\2^" "$TCPATH/$TMP_SRC_DIR/$COMPONENT/Makefile"
	${VF_OSCFG_SED} ${VF_OSCFG_SED_EXTPARAM} ${VF_OSCFG_SED_INLPARAM} "s^(AFLAGS *= *.* *)BUILD_INSERTS_AFLAGS_HERE(\\s.*)?^\1$AFLAGS\2^" "$TCPATH/$TMP_SRC_DIR/$COMPONENT/Makefile"
	${VF_OSCFG_SED} ${VF_OSCFG_SED_EXTPARAM} ${VF_OSCFG_SED_INLPARAM} "s^(LFLAGS *= *.* *)BUILD_INSERTS_LFLAGS_HERE(\\s.*)?^\1$LFLAGS\2^" "$TCPATH/$TMP_SRC_DIR/$COMPONENT/Makefile"
	${VF_OSCFG_SED} ${VF_OSCFG_SED_EXTPARAM} ${VF_OSCFG_SED_INLPARAM} "s^(LOOSE_OBJECTS *= *.* *)BUILD_INSERTS_LOOSE_OBJECTS_HERE(\\s.*)?^\1$LOOSE_OBJECTS\2^" "$TCPATH/$TMP_SRC_DIR/$COMPONENT/Makefile"
  
	# Generate the Make.deps dependency file.    
	pushd $TCPATH/$TMP_SRC_DIR/$COMPONENT >/dev/null
	local PARENT_SOURCE_FILE=$(find . -name ${EXECUTABLE##*/}.cpp -o -name ${EXECUTABLE##*/}.c -o -name ${EXECUTABLE##*/}.s | ${VF_OSCFG_SED} "s^[.]/^^g" | grep -E "^${EXECUTABLE}[.](cpp|c|s)")
	generate_component_dependencies . ${PARENT_SOURCE_FILE}
	popd >/dev/null

	# Actually make the component.
	echo -e "${CYAN}Making component $COMPONENT ...\n${NO_COLOUR}"
	make -C "$TCPATH/$TMP_SRC_DIR/$COMPONENT" all

	# NOTE - Don't put anything in here; we need the return value from 'make' below.

	# Check the return value from make, to determine if an error occurred during compilation.
	if [ $? != 0 ]; then
		# Something went wrong.
		echo -e "\n${RED}Compilation error.  Failed to build component $COMPONENT.\n${NO_COLOUR}"
		return 1
	fi
	
	# The compilation worked, so now just copy across the output binaries.
	mkdir -p $TCPATH/$OUTPUT_DIR/$COMPONENT
	$OBJCOPY -O ihex "$TCPATH/$TMP_SRC_DIR/$COMPONENT/${ARDUINO_SKETCH%.*}" $TCPATH/$OUTPUT_DIR/${COMPONENT}/${COMPONENT_NAME}.hex

	# Check the return value from the object copy.
	if [ $? != 0 ]; then
		# Something went wrong.
		echo -e "\n${RED}Object copy error.  Failed to build component $COMPONENT.\n${NO_COLOUR}"			
		return 1
	fi
	echo -e ""

	# Print out details of the size of the generated hex file.
	echo -e "${WHITE}Output file size details:\n${NO_COLOUR}"
	$SIZE --format=avr --mcu=${MCU_CODE} --totals "$TCPATH/$TMP_SRC_DIR/$COMPONENT/${ARDUINO_SKETCH%.*}"
	$SIZE --format=SysV --totals $TCPATH/$OUTPUT_DIR/${COMPONENT}/${COMPONENT_NAME}.hex

	# All done.
	echo -e "${BOLD_WHITE}Build successful.  Output files written to $OUTPUT_DIR/$COMPONENT.\n${NO_COLOUR}"
	return 0
}

######################################## FUNCTION #########################################
###											###
### Name:		makearduino_bootloader						###
###											###
### Inputs/Outputs:	None								###
###											###
### Purpose:		Builds the default Arduino bootloader for the current 		###
###			component.  Since the Arduino IDE comes with a binary version	###
###			the bootloader, this is trivial.			     	###
###											###
###########################################################################################

makearduino_bootloader()
{
	# Set up the Arduino compiler, since it has the bootloader binary.
	unpack_arduinoc

	# Check if the build configuration specifies a bootloader file.
	if [ -n "${BLOAD_ARDUINO_BOOTLOADER}" ]; then
		# Check if this file doesn't actually exist.
		if [ ! -f "$TCPATH/tmp/tmp_compiler/arduino/arduino-dist/${BLOAD_ARDUINO_BOOTLOADER}" ]; then
			# The file doesn't exist, so the bootloader configuration is probably incorrect.
			echo -e "${RED}Bootloader file '${BLOAD_ARDUINO_BOOTLOADER}' not found.  Aborting...\n${NO_COLOUR}"
		fi
	else
		# No file was specified, which indicates the bootloader configuration is incomplete.
		echo -e "${RED}Bootloader configuration incomplete, no Arduino bootloader file specified.  Aborting...\n${NO_COLOUR}"
		return 1
	fi

	# All we need to do is copy over the required file.
	echo -e "${CYAN}Making bootloader for component $COMPONENT ...\n${NO_COLOUR}"
	cp "$TCPATH/tmp/tmp_compiler/arduino/arduino-dist/${BLOAD_ARDUINO_BOOTLOADER}" ${OUTPUT_DIR}/${COMPONENT}/${COMPONENT}_bootloader.hex

	# We don't care about the MCU fuses, but typically Arduino devices lock the bootloader section.
	echo -e "${YELLOW}NOTE - Arduino devices typically lock the bootloader section.  Remember to check fuse settings when uploading.\n${NO_COLOUR}"

	# All done.
	echo -e "${BOLD_WHITE}Build successful.  Output binary written to ${OUTPUT_DIR}/${COMPONENT}/${COMPONENT}_bootloader.hex.\n${NO_COLOUR}"
	return 0
}

