#!/bin/bash

#	Copyright (C) 2011 Unison Networks Ltd
#
#	This program is free software: you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation, either version 3 of the License, or
#	(at your option) any later version.
#
#	This program is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with this program.  If not, see <http://www.gnu.org/licenses/>

###########################################################################################################################
###															###
### Name:		create_component										###
###															###
### Author:		Zac Frank											###
###															###
### Date Created:	15-11-2011											###
###															###
### Type:		Bash Script											###
###															###
### Purpose:		This script gets called by VFstart script, when the user chooses to create a new component. 	###
###			It creates a new folder in src given the name of the component specified by the user, and 	###
###			sets the component configuration depending on the user's input. 				###
###															###
###########################################################################################################################

# FIGURE OUT WHERE WE ARE.

# Determine what the absolute path to the root of the toolchain is.
SCRIPT=`readlink -f $0`
SCRIPTPATH=`dirname $SCRIPT`
TCPATH=$(echo $SCRIPTPATH | sed 's/\/bld.*//')

# DEFINE CONSTANTS.

# Define file names.

TEMPLATE_C_FILE="res/c_template.c"
TEMPLATE_H_FILE="res/h_template.h"
USER_CONFIG_FILE="var/config.cfg"
BUILD_CONFIG_FILE="bld/build_configs.cfg"

# Define the colours used for interface output.
source $TCPATH/bld/common/def_colours

# Define the functions used for preprocessing.
source $TCPATH/bld/preprocess/preprocess

# Define the functions used to set up any vendor sources.
source $TCPATH/bld/other/setup_vendorsources

# Define the functions used to for code generation.
for f in $TCPATH/bld/code_generation/gen_*; do
	source "$f"
done

# Import functions for manipulating config files.
source $TCPATH/bld/common/config_helpers

# Create directories which don't come automatically with the toolchain.
source $TCPATH/bld/common/create_empty_dirs

######################################## FUNCTION #########################################
###											###
### Name:		choose_target							###
###											###
### Inputs/Outputs:	None								###
###											###
### Purpose:		Asks the user which target they are using and sets the value	###
###			$NEW_TARGET accordingly.					###
###											###
###########################################################################################

choose_target()
{
	# List the possible build configurations.
	BCONFS=`declare -F | grep -o -e "declare -f bconf_.*" | grep -o -e "bconf_.*"`
	
	# Check that something was actually returned here.
	if [ -z "$BCONFS" ]; then
		# Something is terribly wrong here.
		echo -e "${BOLD_RED}FATAL - No application build profiles available.\n${NO_COLOUR}"
		exit 1
	fi

	# Iterate through the possible build configurations
	for BCONF in $BCONFS; do
		# Extract the name of the target from the configuration and add it to a list of possible targets.
		TARGETS="`echo $BCONF | cut -d '_' -f 2` $TARGETS"
	done

	# Sort the list of targets and search for duplicates.
	TARGETS="`echo $TARGETS | tr " " "\n" | sort -u -r | tr "\n" " "`"

	# Prompt the user; the message depends on whether this is a new component or not.
	if [ ${NEW} ]; then
		# It's a new component, so there is no precedent to draw from.
		echo -e "${GREEN}Which target would you like to code for? \n${NO_COLOUR}"
	else
		# The component is being reconfigured, so indicate the existing precedent.
		echo -e "${GREEN}Which target would you like to code for? (Currently: ${NO_COLOUR}${TARGET}${GREEN}) \n${NO_COLOUR}"
	fi

	# Create a menu of choices and have the user select one.
	select NEW_TARGET in $TARGETS
	do
		# Check if the selected target is actually valid.
		NEW_TARGET=$(echo "$TARGETS" | grep -w -o "$NEW_TARGET")
		if [ -z "$NEW_TARGET" ]; then
			# The selected target was not in the list of targets, so the user is apparently a moron.
			echo -e -n "${RED}Invalid choice.  Try again. ${NO_COLOUR}"
		else
			# A legitimate option was selected, so we can go now.
			echo -e "${CYAN}Selected target $NEW_TARGET.\n${NO_COLOUR}"
			break
		fi
	done

	# All done.
	return
}

######################################## FUNCTION #########################################
###											###
### Name:		choose_platform							###
###											###
### Inputs/Outputs:	None								###
###											###
### Purpose:		Asks the user which platform (operating system) they wish to	###
###			use and sets the value $NEW_PLATFORM accordingly.		###
###											###
###########################################################################################

choose_platform()
{
	# List the possible build configurations.
	BCONFS=`declare -F | grep -o -e "declare -f bconf_.*" | grep -o -e "bconf_.*"`
	
	# Check that something was actually returned here.
	if [ -z "$BCONFS" ]; then
		# Something is terribly wrong here.
		echo -e "${BOLD_RED}FATAL - No application build profiles available.\n${NO_COLOUR}"
		exit 1
	fi

	# Iterate through the possible build configurations
	for BCONF in $BCONFS; do
		# Check if this configuration is specific to our chosen target.
		if [ "$NEW_TARGET" == `echo $BCONF | cut -d '_' -f 2` ]; then
			# This configuration matches the current target.
	
			# Extract the name of the platform from the configuration and add it to a list of possible platforms.
			PLATFORMS="`echo $BCONF | cut -d '_' -f 3` $PLATFORMS"
		fi
			# Else, the configuration is for some other target, so we ignore it.
	done

	# Sort the list of platforms and search for duplicates.
	PLATFORMS="`echo $PLATFORMS | tr " " "\n" | sort -u -r | tr "\n" " "`"

	# Prompt the user; the message depends on whether this is a new component or not.
	if [ ${NEW} ]; then
		# It's a new component, so there is no precedent to draw from.
		echo -e "${GREEN}Which platform would you like to code for? \n${NO_COLOUR}"
	else
		# The component is being reconfigured, so indicate the existing precedent.
		echo -e "${GREEN}Which platform would you like to code for? (Currently: ${NO_COLOUR}${PLATFORM}${GREEN}) \n${NO_COLOUR}"
	fi

	# Create a menu of choices and have the user select one.
	select NEW_PLATFORM in $PLATFORMS
	do
		# Check if the selected platform is actually valid.
		NEW_PLATFORM=$(echo "$PLATFORMS" | grep -w -o "$NEW_PLATFORM")
		if [ -z "$NEW_PLATFORM" ]; then
			# The selected platform was not in the list of platforms, so the user is apparently a moron.
			echo -e -n "${RED}Invalid choice.  Try again. ${NO_COLOUR}"
		else
			# A legitimate option was selected, so we can go now.
			echo -e "${CYAN}Selected platform $NEW_PLATFORM.\n${NO_COLOUR}"
			break
		fi
	done

	# All done.
	return
}

######################################## FUNCTION #########################################
###											###
### Name:		choose_bootloader						###
###											###
### Inputs/Outputs:	None								###
###											###
### Purpose:		Asks the user which bootloader they wish to use and sets the	###
###			value $NEW_BOOTLOADER accordingly.				###
###											###
###########################################################################################

choose_bootloader()
{
	# List the possible bootloader configurations.
	BLOADCONFS=`declare -F | grep -o -e "declare -f bload_.*" | grep -o -e "bload_.*"`
	
	# Iterate through the possible bootloader configurations
	for BLOADCONF in $BLOADCONFS; do
		# Check if this configuration is specific to our chosen target.
		if [ "$NEW_TARGET" == `echo $BLOADCONF | cut -d '_' -f 2` ]; then
			# This configuration matches the current target.
	
			# Extract the name of the bootloader from the configuration and add it to a list of possible bootloaders.
			BOOTLOADERS="`echo $BLOADCONF | cut -d '_' -f 3` $BOOTLOADERS"
		fi
			# Else, the configuration is for some other target, so we ignore it.
	done

	# Sort the list of bootloaders and search for duplicates.
	BOOTLOADERS="`echo $BOOTLOADERS | tr " " "\n" | sort -u -r | tr "\n" " "`"

	# Check if the list is empty.  It can be, because its possible to have a build configuration for a target without a suitable bootloader.
	if [ -z "${BOOTLOADERS## }" ]; then
		# There are no suitable bootloaders, so there is no point asking the user to choose one.
		echo -e "${YELLOW}No suitable bootloaders found for this target.\n${NO_COLOUR}"
		return
	fi

	# Prompt the user; the message depends on whether this is a new component or not.
	if [ ${NEW} ]; then
		# It's a new component, so there is no precedent to draw from.
		echo -e "${GREEN}Which bootloader would you like to use for this component? \n${NO_COLOUR}"
	else
		# The component is being reconfigured, so indicate the existing precedent.
		if [ -z "${BOOTLOADER}" ]; then BOOTLOADER="None"; fi
		echo -e "${GREEN}Which bootloader would you like to use for this component? (Currently: ${NO_COLOUR}${BOOTLOADER}${GREEN}) \n${NO_COLOUR}"
	fi

	# Create a menu of choices and have the user select one.
	BOOTLOADERS=( "${BOOTLOADERS[@]} None" )
	select NEW_BOOTLOADER in $BOOTLOADERS
	do
		# Check if they chose not to use a bootloader.
		if [ "$NEW_BOOTLOADER" == "None" ]; then
			# We don't use a bootloader.
			echo -e "${CYAN}Not using a bootloader for this component.\n${NO_COLOUR}"
			NEW_BOOTLOADER=
			break
		fi

		# Check if the selected bootloader is actually valid.
		NEW_BOOTLOADER=$(echo "$BOOTLOADERS" | grep -w -o "$NEW_BOOTLOADER")
		if [ -z "$NEW_BOOTLOADER" ]; then
			# The selected bootloader was not in the list of bootloaders, so the user is apparently a moron.
			echo -e -n "${RED}Invalid choice.  Try again. ${NO_COLOUR}"
		else
			# A legitimate option was selected, so we can go now.
			echo -e "${CYAN}Selected bootloader $NEW_BOOTLOADER.\n${NO_COLOUR}"
			break
		fi
	done

	# All done.
	return
}

######################################## FUNCTION #########################################
###																						###
### Name:			choose_executables													###
###																						###
### Inputs/Outputs:	None																###
###																						###
### Purpose:		Asks the user whether or not they want multiple executable files.	###
###			If yes, the user is asked for their names to populate EXECUTABLES.			###
###			Otherwise, it is assumed that the component name is the name of the 		###
###			sole executable file.														###
###																						###
###########################################################################################

choose_executables() {
	# Ask if the user wants multiple executable files.
	echo -e -n "${GREEN}Do you wish to have multiple executable files? (Y/N) ${NO_COLOUR}"
	read -n 1
	echo -e "\n" # Note - this is because the read command won't put a newline after it reads a character.

	# If they responded YES, then ask for the names of the executables.
	if [[ $REPLY =~ ^[Yy]$ ]]; then
		echo -e -n "${GREEN}What are the names of the executables? (Enter the names separated by a space) ${NO_COLOUR}"
		read -e
		echo -e -n "\n" # Note - this is because the read command won't put a newline after it reads a character.

		EXECUTABLES="$REPLY"
		# Update the config file with the executable files.
		push_key ${CONFIG_FILE} "EXECUTABLES" "\"${EXECUTABLES}\""
	else
		# Otherwise, default to one executable with the name of the component.
		EXECUTABLES="$COMPONENT"
	fi
}

##################################### MINOR FUNCTIONS ####################################

# Do any code generation which is required at config time.
generate_code_config_time()
{
	# $1 - Component source directory.

	# Check if the specified location is actually legit.
	if [ ! -d $1 ]; then
		# The specified location is not a directory.
		echo -e "${RED}Invalid source location for code generation.\n${NO_COLOUR}"
		return 1
	fi

	# Check if there is actually some code generation to be done.
	if [ -z "${CODE_GENERATORS_CONFIG_TIME}" ]; then
		# There is nothing to be done here.
		echo -e "${YELLOW}Not performing any configuration time code generation for this build configuration.\n${NO_COLOUR}"
		return 0
	fi

	# Iterate over the list of possible code generation functions.
	echo -e "${CYAN}Running code generators...\n${NO_COLOUR}"
	for f in ${CODE_GENERATORS_CONFIG_TIME}; do
		# Check that this code generator function specified by the build configuration actually exists.
		if [ `declare -f | grep "$f" | wc -l` == 0 ]; then
			# The specified code generator function doesn't exist, so skip this function and move on.
			echo -e "${RED}Build configuration specifies an invalid configuration time code generation function.  Skipping.\n${NO_COLOUR}"
			GENERATE_FUNCTION_INVALID=1
		else
			# The function is legit, so actually run the function.
			$f $1
		fi		
	done
	# Check if any of the code generation functions in the list were invalid.
	if [ ${GENERATE_FUNCTION_INVALID} ]; then
		# One of the specified code generation functions was invalid, so report the failure.
		GENERATE_FUNCTION_INVALID=
		return 1
	fi

	# All done.
	return 0
}

# Run any build configuration specific configuration required.
run_bconf_specific_config()
{
	# Check to see if we can find a matching build configuration.
	BCONF="bconf_${NEW_TARGET}_${NEW_PLATFORM}"
	if [ `declare -f | grep "$BCONF ()" | wc -l` == 0 ]; then
		# No matching build configuration was found, so we can't do the configuration.
		echo -e "${RED}No suitable build configuration found.  Cannot perform target specific configuration.\n${NO_COLOUR}"
		return 1
	fi
	
	# There is a matching build configuration, so load it.
	echo -e "${CYAN}Loading build configuration ($BCONF)...\n${NO_COLOUR}"
	$BCONF

	# Load (or reload) the component specific configuration, in case there is something component specific which will override the build config.
	load_component_config "$TCPATH/src/$COMPONENT/$COMPONENT_NAME.cfg.bak"

	# NOTE - We try loading a backup copy of the component file first, since that would let us see any previous configuration values.

	# Check if a target specific configuration script was detailed in the build configuration.
	if [ -z $TARGET_SPECIFIC_CONFIG ]; then
		# No specific configuration script was specified.
		echo -e "${YELLOW}No target specific configuration required.\n${NO_COLOUR}"
	else
		# Check if the specific configuration script actually exists.
		if [ ! -r ${TCPATH}/${TARGET_SPECIFIC_CONFIG} ]; then
			# The script could not be found, so we have to bail.
			echo -e "${RED}Target configuration script (${TARGET_SPECIFIC_CONFIG}) not found.  Cannot perform target specific configuration.\n${NO_COLOUR}"
			return 1
		fi

		# Run the target specific build configuration script.
		source $TCPATH/$TARGET_SPECIFIC_CONFIG
	fi
	
	# Check if a platform specific configuration script was detailed in the build configuration.
	if [ -z $PLATFORM_SPECIFIC_CONFIG ]; then
		# No specific configuration script was specified.
		echo -e "${YELLOW}No platform specific configuration required.\n${NO_COLOUR}"
	else
		# Check if the specific configuration script actually exists.
		if [ ! -r ${TCPATH}/${PLATFORM_SPECIFIC_CONFIG} ]; then
			# The script could not be found, so we have to bail.
			echo -e "${RED}Platform configuration script (${PLATFORM_SPECIFIC_CONFIG}) not found.  Cannot perform platform specific configuration.\n${NO_COLOUR}"
			return 1
		fi

		# Run the target specific build configuration script.
		source $TCPATH/$PLATFORM_SPECIFIC_CONFIG
	fi

	# All done.
	return 0
}

# Run any bootloader specific configuration required.
run_bload_specific_config()
{
	# Check if a bootloader was specified.
	if [ -z $NEW_BOOTLOADER ]; then
		# No bootloader was specified, so we can skip this.
		echo -e "${YELLOW}No bootloader selected.  Skipping bootloader specific configuration.\n${NO_COLOUR}"
		return 0
	fi

	# Check to see if we can find a matching build configuration.
	BLOAD="bload_${NEW_TARGET}_${NEW_BOOTLOADER}"
	if [ `declare -f | grep "$BLOAD ()" | wc -l` == 0 ]; then
		# No matching bootloader configuration was found, so we can't do the configuration.
		echo -e "${RED}No suitable bootloader configuration found.  Cannot perform target specific configuration.\n${NO_COLOUR}"
		return 1
	fi

	# There is a matching bootloader configuration, so load it.
	echo -e "${CYAN}Loading bootloader configuration ($BLOAD)...\n${NO_COLOUR}"
	$BLOAD

	# Load (or reload) the component specific configuration, in case there is something component specific which will override the build config.
	load_component_config "$TCPATH/src/$COMPONENT/$COMPONENT_NAME.cfg.bak"

	# NOTE - We try loading a backup copy of the component file first, since that would let us see any previous configuration values.

	# Check if a bootloader specific configuration script was detailed in the bootloader configuration.
	if [ -z $BLOAD_SPECIFIC_CONFIG ]; then
		# No specific configuration script was specified.
		echo -e "${YELLOW}No bootloader specific configuration required.\n${NO_COLOUR}"
	else
		# Check if the specific configuration script actually exists.
		if [ ! -r ${TCPATH}/${BCONF_SPECIFIC_CONFIG} ]; then
			# The script could not be found, so we have to bail.
			echo -e "${RED}Bootloader configuration script (${BCONF_SPECIFIC_CONFIG}) not found.  Cannot perform bootloader specific configuration.\n${NO_COLOUR}"
			return 1
		fi

		# Run the bootloader specific build configuration script.
		source $TCPATH/$BLOAD_SPECIFIC_CONFIG
	fi

	# All done.
	return 0
}

# Load component configuration, if one exists.
load_component_config()
{
	# $1 - Specific configuration file to load.  If blank, then use the default.

	# Check if this is a new component.
	if [ ${NEW} ]; then
		# This is a new component, so there will be no file to load.
		return 0
	fi

	# Check if a specific config file to use was specified.
	if [ -z "$1" ]; then
		# If no specific file was specified, we just use the default location.
		FILE="$TCPATH/src/$COMPONENT/$COMPONENT_NAME.cfg"			
	elif [ -r $1 ]; then
		# Else, if a specific config file was specified, and actually exists, we use that.
		FILE=$1
	else
		# Else we're back to just using the default file location.
		FILE="$TCPATH/src/$COMPONENT/$COMPONENT_NAME.cfg"
	fi

	# Check if we can find the config file for this component.
	if ! [ -r "$FILE" ]; then
		# The configuration file isn't there; so we'll just have to rebuild the file as though it were for a new component.
		echo -e "${RED}No configuration file found for component $COMPONENT; a replacement will need to be created.\n${NO_COLOUR}"
		NEW=1
	else
		# Extract relevant configuration information from the configuration file.
		echo -e "${CYAN}Loading component configuration file...\n${NO_COLOUR}"
		source "$FILE" 
	fi	

	# All done.
	return 0
}

# Print a usage message.
usage()
{
	# Block-concatenate the message.
	cat << EOF

Usage: $0 [Options]

This script is used, as part of the 'Valley Forge' Embedded Toolchain to create components and update their configurations.

Options:
	-h --help			Show this message.
	-b --batch			Operate in 'batch mode', wherein there are no interactive prompts.
	-c --component <Component Name>	Specify the name of a component to create/update.
	-s --subsystem <Subsystem Name>	Specify the name of the subsystem this component is part of.
	-t --target <Target ID>		Specify the target for this component.
	-p --platform <Platform ID>	Specify the platform for this component.
	-l --loader <Bootloader ID>	Specify the bootloader for this component.
EOF
	# All done.
	return 0
}

################################ SCRIPT PROPER STARTS HERE ###############################

# PARSE ANY COMMAND LINE PARAMETERS.

# Reset fields to be extracted from the parameters.
COMPONENT=
BATCHMODE=
NEW_SUBSYSTEM=
NEW_TARGET=
NEW_PLATFORM=
NEW_BOOTLOADER=

# Define variables required for 'getopt' to work.
PROGNAME=${0##*/} 
SHORTOPTS="hbc:s:t:p:l:"
LONGOPTS="help,batch,component:,subsystem:,target:,platform:,loader:"

# Use 'getopt' to parse the command line options.
ARGS=$(getopt -s bash --options $SHORTOPTS --longoptions $LONGOPTS --name $PROGNAME -- "$@")
eval set -- "$ARGS"

# Handle the parsed parameters.
while true; do
	# Select the appropriate behaviour for each parameter.
	case $1 in
		-h|--help)
			# Just print the usage message and then exit.
			usage
			exit 0
			;;
		-b|--batch)
			# Select batch mode.
			BATCHMODE=1
			;;
		-c|--component)
			# Specify the name of the component to create.
			shift
			COMPONENT="$1"
			;;
		-s|--subsystem)
			# Specify the subsystem of the component to create.
			shift
			NEW_SUBSYSTEM="$1"
			;;
		-t|--target)
			# Specify the target of the component to create.
			shift
			NEW_TARGET="$1"
			;;
		-p|--platform)
			# Specify the platform of the component to create.
			shift
			NEW_PLATFORM="$1"
			;;
		-l|--loader)
			# Specify the bootloader of the component to create.
			shift
			NEW_BOOTLOADER="$1"
			;;
		--)
			# We're done parsing options.  We ignore anything else.
			shift
			break
			;;
		*)
			# We ignore anything else.
			shift
			break
			;;
	esac

	# Advance on to the next parameter.
	shift
done

# Parse the build configurations file.
source $TCPATH/bld/common/load_build_configs

# FIGURE OUT THE NAME OF THE COMPONENT WE'RE SUPPOSED TO BE DEALING WITH.

# We'll need a list of existing components.
COMPONENTS=`find ${TCPATH}/src -name '*.cfg' | sed "s/.*\/src\///g" | sed "s/\/[^/]*\.cfg//g"`

# Check if we have been supplied the name of the component to create and that we're not in batch mode.
if [ -z $COMPONENT ] && [ ! $BATCHMODE ]; then
	# Since the user might be a moron and keep entering invalid names, we loop until a suitable name is entered.
	while :
	do
		# We will need to prompt the user for the name of the component to create.
		echo -e -n "${GREEN}Enter a name for the component to be created: (No spaces) ${NO_COLOUR}"
		read
		echo -e "" 

		# Check the user actually entered something.
		if [ -z "$REPLY" ]; then
			# We'll just prompt again.
			continue

		# Check if the user actually just wants to exit without creating anything.
		elif [ "$REPLY" == "exit" ]; then
			# Exit the script.
			exit 0

		# Check if the name is a reserved word.
		elif [ "$REPLY" == "none" ] || [ "$REPLY" == "--retain" ] || [ "$REPLY" == "-r" ] || [ "$REPLY" == "--all" ] ||\
		     [ "$REPLY" == "all" ] || [ "$REPLY" == "-a" ] || [ "$REPLY" == "--help" ] || [ "$REPLY" == "-h" ] ||\
		     [ "$REPLY" == "--clean" ] || [ "$REPLY" == "-c" ]; then
			# The name is a reserved word, and thus invalid.  Prompt the user to choose a more suitable name.
			echo -e "${RED}The component name '$REPLY' is an invalid name.  Please choose another name.\n${NO_COLOUR}"

		# Check if the component name contains spaces.
		elif [[ $REPLY == *\ * ]]; then
			# The name contains spaces, which is invalid. Prompt the user to choose a more suitable name.
			echo -e "${RED}The component name must not contain spaces.  Please choose another name.\n${NO_COLOUR}"

		# Check if the component name starts with a slash, which would suggest an unnamed subdirectory.
		elif [[ $REPLY == /* ]]; then
			# The name starts with a slash, which is invalid.  Prompt the user to choose a more suitable name.
			echo -e "${RED}The component name must not start with a slash (that creates a directory with no name).  Please choose another name.\n${NO_COLOUR}"

		# Check to see if this name is already taken.
		elif [ -n "$(echo $COMPONENTS | grep \\\<$REPLY\\\>)" ]; then
			# The name provided is already taken.  Prompt the user to choose an available name.
			echo -e "${RED}The component '$REPLY' already exists.  Please choose another name.\n${NO_COLOUR}"

		# Check if the component name would be nested INSIDE another component.
		elif [ -n "$(for C in $COMPONENTS; do echo $(echo $REPLY | grep $C); done)" ]; then
			# The nesting passes through another component, which isn't legit.
			echo -e "${RED}The component cannot be nested INSIDE another component.  Please choose another name.\n${NO_COLOUR}"

		# Check if the name contains a slash, and hence will be nested.
		elif [[ $REPLY == */* ]]; then
			# The name contains a slash, so just check that the user knows are trying to create a nested directory.	
			echo -e "${YELLOW}The name '$REPLY' creates a nested source folder structure."
			COMPONENT=$REPLY

			# Ask if the user wants is sure that is what they want.
			echo -e -n "${GREEN}Do you wish to create a nested component directory? (Y/N) ${NO_COLOUR}"
			read -n 1
			echo -e "\n" # NOTE - This is because the read command won't put a newline after it reads a character.	

			# If they responded YES, then we move on.
			if [[ $REPLY =~ ^[Yy]$ ]]; then
				break
			fi

			# Otherwise go back and prompt the user for a different name.
			COMPONENT=

		else
			# The name is probably legit, so we move on.
			COMPONENT=$REPLY
			break
		fi
	done

# Check if we have been supplied the name of the component to create and that we're in batch mode.
elif [ -z $COMPONENT ] && [ $BATCHMODE ]; then
	# We haven't been given a name, and we're in batch mode, so can't ask.  So we just have to bail.
	echo -e "${BOLD_RED}FATAL - No name supplied in batch mode.\n${NO_COLOUR}"
	exit 1
fi

# BECAUSE THIS SCRIPT ALSO HANDLES RECONFIGURATIONS, WE MIGHT NEED TO LOAD SOME COMPONENT CONFIGURATION VARIABLES.

# Since the component might be nested, figure out what the actual name of the component will be.
COMPONENT_NAME=${COMPONENT##*/}

# Reset any variables which may have been set by a previous component.
source $TCPATH/bld/common/clear_bconf_vars
source $TCPATH/bld/common/clear_component_vars

# Check if the name component already exists in the list of components.  This is legitimate, because the 'create' script is also used to reconfigure an existing component.
if [ -n "$(echo \"${COMPONENTS}\" | grep \"^${COMPONENT}\$\")" ]; then
	# The component already exists, so we're just reconfiguring it.
	echo -e "${CYAN}Component ${COMPONENT} already exists; the component will be reconfigured.\n${NO_COLOUR}"
	NEW=

	# Load the component's existing configuration file, so the user only has to change the values which require modification.
	load_component_config
else
	# The component doesn't exist, so we're creating a new component.
	echo -e "${CYAN}Creating a new component with name ${COMPONENT}.\n${NO_COLOUR}"
	NEW=1
fi

# PROMPT THE USER FOR ANY ADDITIONAL INFORMATION.

# Check if we have been supplied the sub-system name and that we're not in batch mode.
if [ -z $NEW_SUBSYSTEM ] && [ ! $BATCHMODE ]; then
	# We haven't been given a subsystem name, so we need the user to enter one.

	# We will need to prompt the user for the name of the component to create.
	echo -e -n "${GREEN}Enter a subsystem name for the component:${NO_COLOUR}"
	read -e -i "${SUBSYSTEM}" -p " "
	echo -e ""

	# Pretty much anything goes here.
	NEW_SUBSYSTEM=$REPLY

	# TODO - Maybe later we could have a list of known subsystems from which to choose of just a random text field?
fi

# Check if we have been supplied the target type and that we're not in batch mode.
if [ -z $NEW_TARGET ] && [ ! $BATCHMODE ]; then
	# We haven't been given a target type, so we need the user to select one.
	choose_target
fi

# Check if we have been supplied the platform type and that we're not in batch mode.
if [ -z $NEW_PLATFORM ] && [ ! $BATCHMODE ]; then
	# We haven't been given the platform type, so we need the user to select one.
	choose_platform
fi

# Check if we have been supplied the bootloader type and that we're not in batch mode.
if [ -z $NEW_BOOTLOADER ] && [ ! $BATCHMODE ]; then
	# We haven't been given the bootloader type, so we need the user to select one.
	choose_bootloader
fi

# CREATE THE COMPONENT.

# Figure out what the component's configuration file should be.
CONFIG_FILE="$TCPATH/src/$COMPONENT/$COMPONENT_NAME.cfg"

# Check if we're creating a new component, as opposed to just reconfiguring one.
if [ ${NEW} ]; then
	# This is a new component, so we will need to create a directory for it.
	echo -e "${CYAN}Creating component directory (src/$COMPONENT)...\n${NO_COLOUR}"
	mkdir -p $TCPATH/src/$COMPONENT
	echo -e "${CYAN}Creating configuration file (src/$COMPONENT/$COMPONENT_NAME.cfg)...\n${NO_COLOUR}"
	echo -e "# Configuration file for component $COMPONENT_NAME.\n" > ${CONFIG_FILE}
fi

# TODO - We should check that this actually worked, and if it didn't, bail.

# Populate the configuration file for the component.
echo -e "${CYAN}Populating configuration file (src/$COMPONENT/$COMPONENT_NAME.cfg)...\n${NO_COLOUR}"
push_key ${CONFIG_FILE} "SUBSYSTEM" "\"${NEW_SUBSYSTEM}\""
push_key ${CONFIG_FILE} "TARGET" "${NEW_TARGET}"
push_key ${CONFIG_FILE} "PLATFORM" "${NEW_PLATFORM}"
push_key ${CONFIG_FILE} "BOOTLOADER" "${NEW_BOOTLOADER}"

# TODO - We should actually check if this works.

# TARGET SPECIFIC CONFIGURATION.

# Run any required target/platform specific config.
run_bconf_specific_config

# Check if we have been supplied some executable names and that we're not in batch mode.
if [ -z $EXECUTABLES ] && [ ! $BATCHMODE ] && [ ! -z $MULTIPLE_EXECUTABLES ] && [ $NEW ]; then
	# Offer the user the opportunity to define some custom executable names.
	choose_executables
else
	# Only one executable. Do nothing.
	:
fi

# Run any required bootloader specific config.
run_bload_specific_config

# CONFIGURATION-TIME CODE GENERATION.

# Perform any required configuration time code generation.
generate_code_config_time $TCPATH/src/$COMPONENT

# POST-NEW-COMPONENT OPTIONS.

# We only ask the user questions if we're not in batch mode and it's a new component.
if [ ! $BATCHMODE ] && [ $NEW ]; then
	# Ask if the user wants to set this as the current component.
	echo -e -n "${GREEN}Do you wish to make this the current component? (Y/N) ${NO_COLOUR}"
	read -n 1
	echo -e "\n" # NOTE - This is because the read command won't put a newline after it reads a character.	

	# If they responded YES, then set the current component.
	if [[ $REPLY =~ ^[Yy]$ ]]; then
		# We want to set this as the current component.
		sed -i "s^\(tc_curr *= *\).*^\1$COMPONENT^" $TCPATH/$USER_CONFIG_FILE

		# TODO - We should actually check if we can find the config file first.
	fi

	# Ask if the user wants template files to be created.
	echo -e -n "${GREEN}Do you wish for template files to be created for the component? (Y/N) ${NO_COLOUR}"
	read -n 1
	echo -e "\n" # NOTE - This is because the read command won't put a newline after it reads a character.	

	# If they responded YES, then create the template files.
	if [[ $REPLY =~ ^[Yy]$ ]]; then
		# Prompt the user to select a file type.
		echo -e "${GREEN}Please choose which file type to create:${NO_COLOUR}"
		# Create a menu of choices and have the user select one.
		select TYPE in C CPP
		do
			# Check if the selected file type is actually valid.
			TYPE=$(echo "C CPP" | grep -w -o "$TYPE")
			if [ -z "$TYPE" ]; then
				# The selected file type was not in the list of supported types, so the user is apparently a moron.
				echo -e "${RED}Invalid choice.  Try again.\n${NO_COLOUR}"
			else
				# A legitimate option was selected, so we can go now.
				echo -e "${CYAN}Selected file type $TYPE.\n${NO_COLOUR}"
				break
			fi
		done

		# Create the template files.
		for EXEC_NAME in $EXECUTABLES
		do
			echo -e "${GREEN}Creating executable: ${EXEC_NAME}${NO_COLOUR}"
			bash $TCPATH/bld/create/create_files -n $EXEC_NAME -c $COMPONENT -t "$TYPE" -b
		done
	fi

	# Explain to the user what they should do now.
	echo -e "${BOLD_WHITE}The working directory for component $COMPONENT_NAME can now be found at src/$COMPONENT.\n${NO_COLOUR}"
fi

# All done.
echo -e "${CYAN}All done.\n${NO_COLOUR}"
exit 0

