#!/usr/bin/env bash

#	Copyright (C) 2011 Unison Networks Ltd
#
#	This program is free software: you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation, either version 3 of the License, or
#	(at your option) any later version.
#
#	This program is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with this program.  If not, see <http://www.gnu.org/licenses/>

###########################################################################################################################
###															###
### Name:		create_library_files										###
###															###
### Author:		Edwin Hayes											###
###															###
### Date Created:	15-11-2011											###
###															###
### Type:		Bash Script											###
###															###
### Purpose:		This script is used to create a new set of blank source files in an existing library, from	###
###			the available template files. 									###
###															###
###########################################################################################################################

# MAKE SURE WE'RE IN A SANE ENVIRONMENT.

# Determine which operating system we are using.
VF_OS="$(uname)"
unset VF_OS_DARWIN
unset VF_OS_LINUX
if [ "${VF_OS}" == "Darwin" ]; then
	VF_OS_DARWIN=1
	VF_OSCFG_READLINK='greadlink'
	VF_OSCFG_SED='gsed'
	VF_OSCFG_SED_EXTPARAM='-E'
	VF_OSCFG_SED_INLPARAM='-i'
else
	VF_OS_LINUX=1
	VF_OSCFG_READLINK='readlink'
	VF_OSCFG_SED='sed'
	VF_OSCFG_SED_EXTPARAM='-r'
	VF_OSCFG_SED_INLPARAM='-i'
fi

# Check if we've got a sufficiently advanced version of BASH to actually run the toolchain.
if [[ ${BASH_VERSINFO[0]} < 4 ]]; then
	# BASH version before v4 are missing things we required, such as "read -i".
	echo -e "\033[0;31mBASH versions prior to 4.x are not supported.  Upgrade to a never version of BASH."
	exit 1
fi

# Check if all the tools we're expecting are installed.
VF_REQUIRED="${VF_OSCFG_READLINK} ${VF_OSCFG_SED}"
for VF_REQUIRED_ITEM in ${VF_REQUIRED}; do
	if [ -z "$(which ${VF_REQUIRED})" ]; then
		echo -e "\033[0;31mUnabled to find: ${VF_REQUIRED}.  Install this utility then try again."
		exit 1
	fi
done
unset VF_REQUIRED_ITEM
unset VF_REQUIRED

# Determine what the absolute path to the root of the toolchain is.
VF_SCRIPTPATH=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
TCPATH=$(echo $VF_SCRIPTPATH | ${VF_OSCFG_SED} 's/\/bld.*//')

# DEFINE CONSTANTS.

# Define file names.

TEMPLATE_C_FILE="res/templates/c_template.c"
TEMPLATE_CPP_FILE="res/templates/cpp_template.cpp"
TEMPLATE_H_FILE="res/templates/h_template.h"
TEMPLATE_HPP_FILE="res/templates/hpp_template.hpp"
USER_CONFIG_FILE="var/config.cfg"
BUILD_CONFIG_FILE="bld/build_configs.cfg"
LIB_SOURCE_PATH="lib"

# Define the colours used for interface output.
source $TCPATH/bld/common/def_colours

# Define the functions used for preprocessing.
source $TCPATH/bld/preprocess/preprocess

# Create directories which don't come automatically with the toolchain.
source $TCPATH/bld/common/create_empty_dirs

##################################### MINOR FUNCTIONS ####################################

# Print a usage message.
usage()
{
	# Block-concatenate the message.
	cat << EOF

Usage: $0 [Options] [File Name]

This script is used, as part of the 'Valley Forge' Embedded Toolchain to create empty source files to develop 
a library with.

Parameters:

	[File Name]			Specify the name of the files to add to the current project, space separated without extension.

Options:
	-h --help			Show this message.
	-b --batch			Operate in 'batch mode', wherein there are no interactive prompts.
	-l --library <Library Name>	Specify the name of the library to which to add files to.
	-n --name <File Name>		Specify the name of the files to add.
	-t --type <File Type>		Specify the kind of files to create (either 'C' or 'CPP').
EOF
	# All done.
	return
}

################################ SCRIPT PROPER STARTS HERE ###############################

# PARSE ANY COMMAND LINE PARAMETERS.

# Reset fields to be extracted from the parameters.
FILENAMES=
BATCHMODE=
LIBRARY=
TYPE=

# Define variables required for 'getopt' to work.
PROGNAME=${0##*/} 
SHORTOPTS="hbn:l:"
LONGOPTS="help,batch,name:,library:"

# Use 'getopt' to parse the command line options.
if [ VF_OS_DARWIN ]; then
	ARGS=$(getopt $SHORTOPTS "$*")
else
	ARGS=$(getopt -s bash --options $SHORTOPTS --longoptions $LONGOPTS --name $PROGNAME -- "$@")
fi
eval set -- "$ARGS"

# Handle the parsed parameters.
while true; do
	# Select the appropriate behaviour for each parameter.
	case $1 in
		-h|--help)
			# Just print the usage message and then exit.
			usage
			exit 0
			;;
		-b|--batch)
			# Select batch mode.
			BATCHMODE=1
			;;
		-n|--name)
			# Specify the name of the files to create.
			shift
			FILENAMES="$FILENAMES$1 " # NOTE - The space in intentional!
			;;
		-l|--library)
			# Specify the name of the library to add files to.
			shift
			LIBRARY="$1"
			;;
		-t|--type)
			# Specify the type of files to create.
			shift
			TYPE="$1"
			;;
		--)
			# We're done parsing options.  Anything else must be parameters.
			shift
			FILENAMES="$FILENAMES$* " # NOTE - The space in intentional!
			break
			;;
		*)
			# Anything else must be parameters.
			shift
			FILENAMES="$FILENAMES$* " # NOTE - The space in intentional!
			break
			;;
	esac

	# Advance on to the next parameter.
	shift
done

# PROMPT THE USER FOR ANY ADDITIONAL INFORMATION.

# Check if we were told which component to add files to and that we're not in batch mode.
if [ -z $LIBRARY ] && [ ! $BATCHMODE ]; then
	# Check if there actually are any libraries to choose from.
	ls -d $TCPATH/$LIB_SOURCE_PATH/*/ >/dev/null 2>&1
	if [ $? != 0 ]; then
		# There are no libraries, so bail.
		echo -e "${YELLOW}No suitable libraries available to add files to.\n${NO_COLOUR}"
		exit 0
	fi

	# Prompt the user with a list of libraries and have them choose one.
	echo -e "${GREEN}Select which library to add files to: \n${NO_COLOUR}"

	# Create a menu of choices and have the user select one.
	select LIBRARY in $(ls $TCPATH/$LIB_SOURCE_PATH)
	do
		# Check if the selected library is actually valid.
		LIBRARY=$(echo "$(ls $TCPATH/$LIB_SOURCE_PATH)" | grep -w -o "$LIBRARY")
		if [ -z "$LIBRARY" ]; then
			# The selected library was not in the list of libraries, so the user is apparently a moron.
			echo -e "${RED}Invalid choice.  Try again.\n${NO_COLOUR}"
		else
			# A legitimate option was selected, so we can go now.
			echo -e "${BOLD_CYAN}Selected library $LIBRARY.\n${NO_COLOUR}"
			break
		fi
	done

# Check if we have been told which component to add files to and that we're in batch mode.
elif [ -z $LIBRARY ] && [ $BATCHMODE ]; then
	# We haven't been given a library, and we're in batch mode, so can't ask.  So we just have to bail.
	echo -e "${RED}No library specified in batch mode.\n${NO_COLOUR}"
	exit 1
fi

# Check if the specified library actually exists.
if [ ! -d $TCPATH/$LIB_SOURCE_PATH/$LIBRARY ]; then
	# The library does't have a matching folder, so we bail.
	echo -e "${RED}Library $LIBRARY does not exist.\n${NO_COLOUR}"
	exit 1
fi

# Check if we have been supplied the name of some files to create and that we're not in batch mode.
if [ -z $FILENAMES ] && [ ! $BATCHMODE ]; then
	# We haven't been given a file name, so we need the user to enter one.

	# We will need to prompt the user for the name of the component to create.
	echo -e -n "${GREEN}Enter basenames for the files to be created: (Space separated) ${NO_COLOUR}"
	read
	echo -e ""

	# Pretty much anything goes here.
	FILENAMES=$REPLY

# Check if we have been supplied the name of some files to create and that we're in batch mode.
elif [ -z $FILENAMES ] && [ $BATCHMODE ]; then
	# We haven't been given a filename, and we're in batch mode, so can't ask.  So we just have to bail.
	echo -e "${RED}No filenames supplied in batch mode.\n${NO_COLOUR}"
	exit 1
fi

# Check if we have been told which type of files to create and that we're not in batch mode.
if [ -z $TYPE ] && [ ! $BATCHMODE ]; then
	# We haven't been given a type, so we need the user to enter one.

	# Prompt the user to select a file type.
	echo -e "${GREEN}Please choose which file type to create:${NO_COLOUR}"
		# Create a menu of choices and have the user select one.
		select TYPE in "C CPP"
		do
			# Check if the selected file type is actually valid.
			TYPE=$(echo "C CPP" | grep -w -o "$PINS")
			if [ -z "$TYPE" ]; then
				# The selected file type was not in the list of supported types, so the user is apparently a moron.
				echo -e "${RED}Invalid choice.  Try again.\n${NO_COLOUR}"
			else
				# A legitimate option was selected, so we can go now.
				echo -e "${CYAN}Selected file type $TYPE.\n${NO_COLOUR}"
				break
			fi
		done

# Check if we have been told which type of files to create and that we're in batch mode.
elif [ -z $TYPE ] && [ $BATCHMODE ]; then
	# We haven't been given a type, and we're in batch mode, so can't ask.  So we just have to bail.
	echo -e "${RED}No file type specified in batch mode.\n${NO_COLOUR}"
	exit 1

# Check if we're been told to create an invalid type of file.
elif ( ! $TYPE == "C" ) && ( ! $TYPE == "CPP"); then
	# An invalid file type was specified.
	echo -e "${RED}Invalid file type ($TYPE). Use either 'C' or 'CPP'.\n${NO_COLOUR}"
	exit 1
fi

# CREATE THE FILES.

# Since the library might be nested, figure out what the actual name of the library will be.
LIBRARY_NAME=${LIBRARY##*/}

# Parse the build configurations file.
source $TCPATH/bld/common/load_build_configs

# Check if we can find the config file for this library.
if ! [ -r $TCPATH/$LIB_SOURCE_PATH/$LIBRARY/$LIBRARY_NAME.cfg ]; then
	# The configuration file isn't there.  Ask the user if they want to create the file, or skip this library.
	echo -e "${RED}No configuration file found for library $LIBRARY.\n${NO_COLOUR}"
	echo -e -n "${GREEN}Do you wish to create the missing configuration file now? (Y/N) ${NO_COLOUR}"
	read -n 1
	echo -e "\n" # NOTE - This is because the read command won't put a newline after it reads a character.
		
	# If they responded YES, then rebuild the configuration file.  If NO, then we bail.
	if [[ $REPLY =~ ^[Yy]$ ]]; then
		# Rebuild the configuration file.
			
		# Call the 'create_library' script: it will handle rebuilding the configuration file.
		bash $TCPATH/bld/create/create_library --name $LIBRARY

		# TODO - Need to check that this actually worked.  If it didn't, then we need to bail.
	else
		# Just skip this component and move on.
		echo -e "${YELLOW}No configuration file.  Cannot create files for library $LIBRARY.\n${NO_COLOUR}"
		exit 0
	fi
fi

# Extract relevant configuration information from the configuration file.
BUILDS=$(grep -v "#" $TCPATH/$LIB_SOURCE_PATH/$LIBRARY/$LIBRARY_NAME.cfg | grep "^BUILDS" | cut -d '=' -f2)

# Iterate through all the filenames in the list provided.
echo -e "${CYAN}Creating template files...\n${NO_COLOUR}"
for FILENAME in $FILENAMES; do
	# TODO - Check if there is already a file which the specified name in the source directory.

	# Check which kind of file we are creating.
	if [ $TYPE == "C" ]; then
		# Create the actual files by coping the templates into the source directory.
		cp $TCPATH/$TEMPLATE_C_FILE $TCPATH/$LIB_SOURCE_PATH/$LIBRARY/$FILENAME.c
		cp $TCPATH/$TEMPLATE_H_FILE $TCPATH/$LIB_SOURCE_PATH/$LIBRARY/$FILENAME.h

		# Preprocess the two template files.
		preprocess_template $TCPATH/$LIB_SOURCE_PATH/$LIBRARY/$FILENAME.c
		preprocess_template $TCPATH/$LIB_SOURCE_PATH/$LIBRARY/$FILENAME.h
	elif [ $TYPE == "CPP" ]; then
		# Create the actual files by coping the templates into the source directory.
		cp $TCPATH/$TEMPLATE_CPP_FILE $TCPATH/$LIB_SOURCE_PATH/$LIBRARY/$FILENAME.cpp
		cp $TCPATH/$TEMPLATE_HPP_FILE $TCPATH/$LIB_SOURCE_PATH/$LIBRARY/$FILENAME.hpp

		# Preprocess the two template files.
		preprocess_template $TCPATH/$LIB_SOURCE_PATH/$LIBRARY/$FILENAME.cpp
		preprocess_template $TCPATH/$LIB_SOURCE_PATH/$LIBRARY/$FILENAME.hpp
	fi
done

# All done.
echo -e "${CYAN}All done.\n${NO_COLOUR}"	
exit 0


