#!/usr/bin/env bash

#	Copyright (C) 2013 Unison Networks Ltd
#
#	This program is free software: you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation, either version 3 of the License, or
#	(at your option) any later version.
#
#	This program is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with this program.  If not, see <http://www.gnu.org/licenses/>

###########################################################################################################################
###															###
### Name:		gen_gitcommit								###
###															###
### Author:		James Morritt								###
###															###
### Date Created:	10-02-2013								###
###															###
### Type:		Bash Script									###
###															###
### Purpose:		Provides functions which generate code which implements the git commit. 	###
###															###
###########################################################################################################################

# Indicate the file was imported successfully.
echo -e "${CYAN}Imported git commit code generation functions.\n${NO_COLOUR}"

######################################## FUNCTION #########################################
###											###
### Name:		gen_gitcommit							###
###											###
### Inputs/Outputs:	Takes the path to the source location where to generate code.	###
###											###
### Purpose:		Generates files which implements the git commit.	###
###											###
###########################################################################################


gen_gitcommit()
{
    local GEN_CACHE=${TCPATH}/tmp/gen_cache

    # Check if the specified location is actually legit.
	if [ ! -d $1 ]; then
		# The specified location is not a directory.
		echo -e "${RED}Invalid source location for code generation.\n${NO_COLOUR}"
		return 1
	fi
	echo -e "${CYAN}Generating git hash code...\n${NO_COLOUR}"

    local GITHASH=$(git rev-parse --short HEAD)


    echo "#ifndef __COMMITID_H__" > "${GEN_CACHE}/githash.h"
    echo "#define __COMMITID_H__" >> "${GEN_CACHE}/githash.h"
    echo "//THIS FILE IS AUTO GENERATED" >> "${GEN_CACHE}/githash.h"
    echo "//DO NOT TRACK THIS FILE WITH THE VCS" >> "${GEN_CACHE}/githash.h"

    echo -n "#define COMMIT_ID ">> "${GEN_CACHE}/githash.h"
    echo "\"${GITHASH}\"">>"${GEN_CACHE}/githash.h"
    echo "#endif /*__COMMITID_H__*/" >> "${GEN_CACHE}/githash.h"

    echo -e "${CYAN}\tCopying across generated git hash file...\n${NO_COLOUR}"
    cp -rf ${GEN_CACHE}/githash.h $1/githash.h

    return 0
}