#!/bin/bash

#	Copyright (C) 2013 Unison Networks Ltd
#
#	This program is free software: you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation, either version 3 of the License, or
#	(at your option) any later version.
#
#	This program is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with this program.  If not, see <http://www.gnu.org/licenses/>

###########################################################################################################################
###																														###
### Name:		gen_pixhawk																								###
###																														###
### Author:		Zane Barker																								###
###																														###
### Date Created:	26-11-2014																							###
###																														###
### Type:		Bash Script																								###
###																														###
### Purpose:		Provides functions which generate code which implements the Pixhawk platform.		 				###
###																														###
###########################################################################################################################

# Indicate the file was imported successfully.
echo -e "${CYAN}Imported NuttX code generation functions.\n${NO_COLOUR}"

######################################## FUNCTION #########################################
###																						###
### Name:		gen_pixhawk																###
###																						###
### Inputs/Outputs:	Takes the path to the source location where to generate code.		###
###																						###
### Purpose:		Generates files which implements the Pixhawk platform. The 			###
###			generated files will still require the user to make required				###
###			target specific modifications.												###
###																						###
###########################################################################################

gen_pixhawk()
{
	# DEFINE CONSTANTS.

	GEN_CACHE=${TCPATH}/tmp/gen_cache

	# PRIVATE INTERNAL FUNCTIONS.

	# FUNCTION PROPER STARTS HERE.

	# Check if the specified location is actual legit.
	if [ ! -d $1 ]; then
		# The specified location is not a directory.
		echo -e "${RED}Invalid source location for code generation.\n${NO_COLOUR}"
		return 1
	fi
	echo -e "${CYAN}Generating Pixhawk platform code...\n${NO_COLOUR}"

	# Check to see if the required platform configuration settings are present.
	if [ -z "${PIXHAWK_COMMON_SOURCE}" -o -z "${PIXHAWK_TEMPLATE_SOURCE}" ]; then
		# Some of the required platform configuration settings are missing, so we must abort.
		echo -e "${RED}Pixhawk platform configuration incomplete. Cannot generate Pixhawk files.\n${NO_COLOUR}"
		return 1
	fi

	# Unpack the Pixhawk source files across to where they are needed.
	unpack_pixhawk
	if [ $? -ne 0 ]; then
		# We couldn't unpack the Pixhawk source, so we'll have to abort.
		return 1
	fi

	# First, we copy the original Pixhawk source files across to where they are needed.
	echo -e "${CYAN}\tCopying Pixhawk source files into place...\n${NO_COLOUR}"

	# Check if we know of a folder containing patches we should apply.
	if [ -z "${PIXHAWK_PATCHES}" ]; then
		# No patches folder was specified, so presumably we don't need to patch anything.
		echo-e "{YELLOW}\tNot applying any patches to Pixhawk files.\n${NO_COLOUR}"
	elif [ ! -d "${PIXHAWK_PATCHES}" ]; then
		# There is no patches folder, so presumably we don't need to patch anything.
		echo -e "${YELLOW}\tNot applying any patches to Pixhawk files.\n${NO_COLOUR}"
	else
		# Check if there are actually any patches to apply.
		if [ -z "`ls ${PIXHAWK_PATCHES}/*.patch`" ]; then
			# There is nothing in the patches filder, so presumably we don't need to patch anything.
			echo -e "${YELLOW}\tNot applying any patches to Pixhawk files.\n${NO_COLOUR}"
		else
			# Iterate over each of the patch files.
			echo -e "${CYAN}\tPatching NuttX files.\n${NO_COLOUR}"
			for PATCH_FILE in `ls ${PIXHAWK_PATCHES}/*.patch`; do
				# Check if the corresponding file is available in the source tree.
				PATCH_FILE="${PATCH_FILE##*/}"
				if [ -f "$1/nuttx/${PATCH_FILE%.*}" ]; then
					# Copy the patch in next to the original file.
					cp ${NUTTX_PATCHES}/${PATCH_FILE} $1/nuttx/${PATCH_FILE}

					# Apply the patch.
					echo -e "${CYAN}\t\tPatching from '${PATCH_FILE}'.\n${NO_COLOUR}"
					pushd $1/nuttx >/dev/null
					patch --no-backup-if-mismatch -Nf -r - < ${PATCH_FILE}
					popd >/dev/null
					echo ""

					# Delete the patch file again
					rm $1/${PATCH_FILE}
				else
					# Else the file isn't there, so we just skip patching it.
					echo -e "${YELLOW}\t\tNo file to patch from '{PATCH_FILE}'.\n${NO_COLOUR}"
				fi
			done
			PATCH_FILE=
		fi
	fi



	# All done.
	return 0
}

# ALL DONE.