#!/usr/bin/env bash

#	Copyright (C) 2011 Unison Networks Ltd
#
#	This program is free software: you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation, either version 3 of the License, or
#	(at your option) any later version.
#
#	This program is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with this program.  If not, see <http://www.gnu.org/licenses/>

# RESET ANY COMPONENT CONFIGURATION VARIABLES WHICH MAY HAVE BEEN SET PREVIOUSLY.

unset SUBSYSTEM
unset TARGET
unset PLATFORM
unset BOOTLOADER

unset LOADFUNCTION

unset PREPROCESSOR_MASK
unset COMPLIANCE_MASK

unset LOOSE_OBJECTS

unset VF_CROSS_COMPILE_SYSROOT

unset VF_LIB_DEPS

unset VF_NO_HAL

# RESET ANY TARGET SPECIFIC COMPONENT CONFIGURATION VARIABLES WHICH MAY HAVE BEEN SET PREVIOUSLY.

# Build configuration variables.

	# Placeholder variables for template code which hasn't actually been implemented yet.
unset SUNSHINE
unset LOLLIPOP
unset RAINBOW

	# Specific to AVR.
unset CLK_SPEED_IN_MHZ

	# Specific to Arduino.
unset ARDUINO_SKETCH
unset ARDUINO_LIB_DIR
unset ARDUINO_CORE_DIR
unset ARDUINO_VARI_DIR
unset ARDUINO_CORELIB_DIR

# Bootloader configuration variables.

	# Specific to the AVR modular bootloader.
unset BLINK_PORT
unset BLINK_PIN
unset LED_LOGIC
unset FORCE_BL_PORT
unset FORCE_BL_PIN
unset INPUT_LOGIC
unset SHUTDOWNSTATE_MEM

# RESET ANY PLATFORM SPECIFIC COMPONENT CONFIGURATION VARIABLES WHICH MAY HAVE BEEN SET PREVIOUSLY.

	# FreeRTOS configuration variables.
unset FREERTOS_IMPORT_SWTIMER
unset FREERTOS_IMPORT_COROUTINE


