#!/bin/bash

#	Copyright (C) 2011 Unison Networks Ltd
#
#	This program is free software: you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation, either version 3 of the License, or
#	(at your option) any later version.
#
#	This program is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with this program.  If not, see <http://www.gnu.org/licenses/>

# RESET ANY COMPONENT CONFIGURATION VARIABLES WHICH MAY HAVE BEEN SET PREVIOUSLY.

SUBSYSTEM=
TARGET=
PLATFORM=
BOOTLOADER=

LOADFUNCTION=

PREPROCESSOR_MASK=

LOOSE_OBJECTS=

# RESET ANY TARGET SPECIFIC COMPONENT CONFIGURATION VARIABLES WHICH MAY HAVE BEEN SET PREVIOUSLY.

# Build configuration variables.

	# Placeholder variables for template code which hasn't actually been implemented yet.
SUNSHINE=
LOLLIPOP=
RAINBOW=

	# Specific to AVR.
CLK_SPEED_IN_MHZ=

	# Specific to Arduino.
ARDUINO_SKETCH=
ARDUINO_LIB_DIR=
ARDUINO_CORE_DIR=
ARDUINO_VARI_DIR=

# Bootloader configuration variables.

	# Specific to the AVR modular bootloader.
BLINK_PORT=
BLINK_PIN=
LED_LOGIC=
FORCE_BL_PORT=
FORCE_BL_PIN=
INPUT_LOGIC=
SHUTDOWNSTATE_MEM=

# RESET ANY PLATFORM SPECIFIC COMPONENT CONFIGURATION VARIABLES WHICH MAY HAVE BEEN SET PREVIOUSLY.

	# FreeRTOS configuration variables.
FREERTOS_IMPORT_SWTIMER=
FREERTOS_IMPORT_COROUTINE=


