#!/bin/bash

#	Copyright (C) 2011 Unison Networks Ltd
#
#	This program is free software: you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation, either version 3 of the License, or
#	(at your option) any later version.
#
#	This program is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with this program.  If not, see <http://www.gnu.org/licenses/>

# Reset any build configuration variables which may have been set previously.

	# General keys.
unset BCONF_NAME
unset MAKEFUNCTION
unset MAKEFILE
unset IOHEADER
unset STDINTHEADER
unset SRC_IMPORT_FILES
unset LOOSE_OBJECTS
unset RESOURCE_FILES

	# Compilers and flags.
unset C_COMPILER
unset P_COMPILER
unset ASSEMBLER
unset LINKER
unset OBJCOPY
unset OBJDUMP
unset SIZE
unset DEBUGGER
unset CFLAGS
unset PFLAGS
unset AFLAGS
unset LFLAGS

	# HAL specific keys (common).
unset HAL_HEADER_PATH
unset HAL_SOURCE_PATH
unset HAL_EN_LIST

	# Target specific keys (common).
unset TARGET_SPECIFIC_CONFIG
unset FSFUNCTION
unset OUTPUT_TYPE
unset OUTPUT_NAME
unset LINKSCRIPT
unset MCU_CODE
unset FPU_CODE
unset VF_PKG_CONFIG_LIBDIRS

	# Target specific keys (AVR).
unset PORT_COUNT

	# Target specific keys (Arduino).
unset ARDUINO_BOARD_TAG

# Target specific keys (Pixhawk).
unset TARGET_PIXHAWK_DEVICE

# Target specific keys (Raspberry Pi).
unset FLOATABI_CODE

	# Platform specific keys (common).
unset PLATFORM_SPECIFIC_CONFIG
unset TEMPLATE_C_SOURCE
unset TEMPLATE_CPP_SOURCE
unset TEMPLATE_H_SOURCE
unset TEMPLATE_HPP_SOURCE
unset TEMPLATE_SUFFIX
unset MULTIPLE_EXECUTABLES
unset PREPROCESSOR_MASK

	# Platform specific keys (FreeRTOS).
unset FREERTOS_COMMON_SOURCE
unset FREERTOS_PORTABLE_SOURCE
unset FREERTOS_CONFIG_FILE
unset FREERTOS_MEMMAN_FILES
unset FREERTOS_PATCHES

	# Platform specific keys (NuttX).
unset NUTTX_COMMON_SOURCE
unset NUTTX_CONFIG_SOURCE
unset NUTTX_TEMPLATE_SOURCE
unset NUTTX_PATCHES

	# Platform specific keys (Pixhawk)
unset PIXHAWK_COMMON_SOURCE
unset PIXHAWK_TEMPLATE_SOURCE
unset PIXHAWK_PATCHES

	# Platform specific keys (Snappy)
unset VF_PLAT_SNAPPY_OEM_PATH
unset VF_PLAT_SNAPPY_OEM_FILE # INTERNAL.
unset VF_PLAT_SNAPPY_DEV_PATH
unset VF_PLAT_SNAPPY_DEV_FILE # INTERNAL.
unset VF_PLAT_SNAPPY_RELEASE
unset VF_PLAT_SNAPPY_CHANNEL
unset VF_PLAT_SNAPPY_FSSIZE

	# Platform specific keys (Raspberry Pi Prebuild Image).
unset VF_PLAT_RASPI_PREBUILT_IMAGE_PATH

	# Uploading keys (common).
unset UPLOAD_FUNCTIONS

	# Uploading keys (via upload_avrdude).
unset AVRDUDE_PART
unset AVRDUDE_ISPDEVFILE
unset AVRDUDE_ISPDEVTYPE
unset AVRDUDE_LOCKED_BYTEVAL
unset AVRDUDE_UNLOCKED_BYTEVAL

	# Uploading keys (via OpenOCD)
unset OPENOCD_INTERFACE_FILE
unset OPENOCD_TARGET_FILE
unset OPENOCD_COMMAND_FILE

	# Code generation keys (common).
unset CODE_GENERATORS
unset CODE_GENERATORS_CONFIG_TIME

	# Bootloader specific keys (common).
unset BLOAD_NAME
unset BLOAD_SPECIFIC_CONFIG

	# Bootloader specific keys (AVR modular bootloader).
unset BOOTSTART
unset MAX_EEPROM_ADDRESS
unset ACTIVE_MODULE

	# Bootloader specific keys (default Arduino bootloader).
unset BLOAD_ARDUINO_BOOTLOADER




