#!/bin/bash

#	Copyright (C) 2011 Unison Networks Ltd
#
#	This program is free software: you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation, either version 3 of the License, or
#	(at your option) any later version.
#
#	This program is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with this program.  If not, see <http://www.gnu.org/licenses/>

# Reset any build configuration variables which may have been set previously.

BCONF_NAME=
BCONF_SPECIFIC_CONFIG=
C_COMPILER=
P_COMPILER=
ASSEMBLER=
OBJCOPY=
MAKEFUNCTION=
MAKEFILE=
LINKSCRIPT=
MCU_CODE=
IOHEADER=
CFLAGS=
AFLAGS=
LFLAGS=
OUTPUT_TYPE=
OUTPUT_NAME=
HAL_HEADER_PATH=
HAL_SOURCE_PATH=
HAL_EN_LIST=
PORT_COUNT=

CODE_GENERATORS=

FSFUNCTION=

BLOAD_NAME=
BLOAD_SPECIFIC_CONFIG=
BOOTSTART=
MAX_EEPROM_ADDRESS=
ACTIVE_MODULE=

UPLOAD_FUNCTIONS=

AVRDUDE_PART=
AVRDUDE_ISPDEVFILE=
AVRDUDE_ISPDEVTYPE=



