#!/bin/bash

#	Copyright (C) 2011 Unison Networks Ltd
#
#	This program is free software: you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation, either version 3 of the License, or
#	(at your option) any later version.
#
#	This program is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with this program.  If not, see <http://www.gnu.org/licenses/>

# Reset any build configuration variables which may have been set previously.

	# General keys.
BCONF_NAME=
MAKEFUNCTION=
MAKEFILE=
MCU_CODE=
IOHEADER=
SRC_IMPORT_FILES=
LOOSE_OBJECTS=

	# Compilers and flags.
C_COMPILER=
P_COMPILER=
ASSEMBLER=
OBJCOPY=
CFLAGS=
PFLAGS=
AFLAGS=
LFLAGS=

	# HAL specific keys (common).
HAL_HEADER_PATH=
HAL_SOURCE_PATH=
HAL_EN_LIST=

	# Target specific keys (common).
TARGET_SPECIFIC_CONFIG=
FSFUNCTION=
OUTPUT_TYPE=
OUTPUT_NAME=
LINKSCRIPT=

	# Target specific keys (AVR).
PORT_COUNT=

	# Target specific keys (Arduino).
ARDUINO_BOARD_TAG=

	# Platform specific keys (common).
PLATFORM_SPECIFIC_CONFIG=

	# Platform specific keys (FreeRTOS).
FREERTOS_COMMON_SOURCE=
FREERTOS_PORTABLE_SOURCE=
FREERTOS_CONFIG_FILE=
FREERTOS_MEMMAN_FILES=
FREERTOS_PATCHES=

	# Uploading keys (common).
UPLOAD_FUNCTIONS=

	# Uploading keys (via upload_avrdude).
AVRDUDE_PART=
AVRDUDE_ISPDEVFILE=
AVRDUDE_ISPDEVTYPE=
AVRDUDE_LOCKED_BYTEVAL=
AVRDUDE_UNLOCKED_BYTEVAL=

	# Code generation keys (common).
CODE_GENERATORS=
CODE_GENERATORS_CONFIG_TIME=

	# Bootloader specific keys (common).
BLOAD_NAME=
BLOAD_SPECIFIC_CONFIG=

	# Bootloader specific keys (AVR modular bootloader).
BOOTSTART=
MAX_EEPROM_ADDRESS=
ACTIVE_MODULE=

	# Bootloader specific keys (default Arduino bootloader).
BLOAD_ARDUINO_BOOTLOADER=




