#!/bin/bash

#	Copyright (C) 2011 Unison Networks Ltd
#
#	This program is free software: you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation, either version 3 of the License, or
#	(at your option) any later version.
#
#	This program is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with this program.  If not, see <http://www.gnu.org/licenses/>

# PARSE THE BUILD CONFIGURATIONS FILE.

# Indicate we are reading the configuration file.
echo -e "${CYAN}Reading build configuration files...\n${NO_COLOUR}"

# We read all the suitable files in the build configuration path.
BUILD_CONFIG_PATH="bld/build_configs"
BUILD_CONFIG_FILES=$(find ${BUILD_CONFIG_PATH} -name "*.cfg")

# Iterate over each of the files in the path.
COUNT_FILES=0
for BUILD_CONFIG_FILE in $BUILD_CONFIG_FILES; do
	# Check if that file actually exists, in case we matched nothing.
	if [ -e ${BUILD_CONFIG_FILE} ]; then
		# Count one file.
		COUNT_FILES=$[$COUNT_FILES + 1]

		# Then read the contents of the file.
		source $BUILD_CONFIG_FILE
	else
		# This only happens if we couldn't find any suitable files.
		echo -e "${BOLD_RED}FATAL - Could not find any suitable build configuration files.\n${NO_COLOUR}"
		exit 1
	fi
done

# Establish how many configurations were read.
COUNT_TARGETS=`declare -F | grep -o -e "bconf_.*" | wc -l`
COUNT_LOADERS=`declare -F | grep -o -e "bload_.*" | wc -l`

# If no valid configurations were read, then there is no point in going any further.
if [ $COUNT_TARGETS == 0 ]; then
	# Report there were no configurations found, and exit.
	echo -e "${BOLD_RED}FATAL - No valid build configurations were found after reading $COUNT_FILES configuration files.\n${NO_COLOUR}"
	exit 1
else
	# Indicate how many build configurations were found.	
	echo -e "${CYAN}Read in $COUNT_TARGETS build configurations and $COUNT_LOADERS boot loader configurations from $COUNT_FILES configuration files.\n${NO_COLOUR}"
fi

# Leave the scope as we found it.
COUNT_FILES=
COUNT_TARGETS=
COUNT_LOADERS=
BUILD_CONFIG_FILE=
BUILD_CONFIG_PATH=
BUILD_CONFIG_FILES=
	
# ALL DONE.
