#!/bin/bash

#	Copyright (C) 2011 Unison Networks Ltd
#
#	This program is free software: you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation, either version 3 of the License, or
#	(at your option) any later version.
#
#	This program is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with this program.  If not, see <http://www.gnu.org/licenses/>

###########################################################################################################################
###															###
### Name:		edit_user_config										###
###															###
### Author:		Zac Frank											###
###															###
### Date Created:	15-11-2011											###
###															###
### Type:		Bash Script											###
###															###
### Purpose:		Allows the user to edit their configuration settings.				 		###
###															###
###########################################################################################################################

# FIGURE OUT WHERE WE ARE.

# Determine what the absolute path to the root of the toolchain is.
SCRIPT=`readlink -f $0`
SCRIPTPATH=`dirname $SCRIPT`
TCPATH=$(echo $SCRIPTPATH | sed 's/\/bld.*//')

# DEFINE CONSTANTS.

# Define file names.

USER_CONFIG_FILE="var/config.cfg"
DEFAULT_USER_CONFIG_FILE="bld/default_user_config.cfg"
BUILD_CONFIG_FILE="bld/build_configs.cfg"

# Define the colours used for interface output.
source $TCPATH/bld/common/def_colours

# Create directories which don't come automatically with the toolchain.
source $TCPATH/bld/common/create_empty_dirs

################################ SCRIPT PROPER STARTS HERE ###############################

# Loop continuously until the user exits the script.
while :
do
	# Print the prompt to the user.
	echo -e  "${GREEN}Please select an option:\n${NO_COLOUR}"
	echo -en "\t${UNDERLINED}U${NO_COLOUR}SER Name    ${UNDERLINED}R${NO_COLOUR}ERUN User Setup    ${UNDERLINED}Q${NO_COLOUR}UIT${NO_COLOUR}"
	
	# Read a single character input from the user and select the appropriate response.
	read -s -n 1
	echo -e "\n" # NOTE - This is required since read won't add a newline after reading a single character.
	case "$REPLY" in
		"U" | "u" )
			# Prompt the user to enter their name.
			echo -e -n "${GREEN}Please enter your name: ${NO_COLOUR}"
			read
			echo -e ""

			# Update the user name in the configuration file.
			sed "s/tc_authname=.*/tc_authname=$REPLY/g" -i $TCPATH/$USER_CONFIG_FILE
			echo -e "${CYAN}Changed username to $REPLY.\n${NO_COLOUR}"
			
			# We're done here.
			break
			;;

		"R" | "r" )
			# Rerun the 'first time configuration' script.
			bash ${TCPATH}/bld/other/first_run

			# We're done here.
			break
			;;

		"Q" | "q" | "X" | "x" )
			# We're done here.
			break
			;;
	esac
done

# All done.
exit 0

