#!/bin/bash

#	Copyright (C) 2012 Unison Networks Ltd
#
#	This program is free software: you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation, either version 3 of the License, or
#	(at your option) any later version.
#
#	This program is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with this program.  If not, see <http://www.gnu.org/licenses/>

###########################################################################################################################
###
### Name:		makenuttx
###
### Author:		Edwin Hayes
###
### Date Created:	11-12-2014
###
### Type:		Bash Script
###
### Purpose:		Provides functions which makes components using the NuttX platform, which has its own build system.
###
###########################################################################################################################

# Indicate the file was imported successfully.
echo -e "${CYAN}Imported Nuttx make-functions.\n${NO_COLOUR}"

######################################## FUNCTION #########################################
###
### Name:		makenuttx_armcortex
###
### Inputs/Outputs:	None
###
### Purpose:	Makefunction for ARM Cortex-M targets using the NuttX platform.
###
###             Copies both the component source files and the NuttX vendor code into the
###				temporary location, creates the required compile time configuration files,
###				then invokes the NuttX build system, which takes over the build process.
###
###########################################################################################

makenuttx_armcortex()
{
	# Perform the standard precompile routine.
	if ! generic_precompile; then
		# There isn't anything to do.
		echo -e "${YELLOW}Nothing to make for component $COMPONENT.\n${NO_COLOUR}"
		return 1
	fi

	# TODO - Unpacking the compiler won't help, because at the moment NuttX won't use the version we unpack.

	# Set up the native compiler.
	unpack_embeddedarmc

	# Ensure the EXECUTABLES variable is populated with something. If it is empty, assign it the name of the component.
	EXECUTABLES="${EXECUTABLES:-${COMPONENT_NAME}}"

	# Generate applications for the executables in the project.
	if ! makenuttx_configure_apps $TCPATH/$TMP_SRC_DIR/$COMPONENT; then
		# Something went wrong.
		echo -e "${RED}Unable to generate application configurations for NuttX.\n${NO_COLOUR}"
		return 1
	fi

	# Actually make the component.
	echo -e "${CYAN}Making component $COMPONENT ...\n${NO_COLOUR}"
	make -C $TCPATH/$TMP_SRC_DIR/$COMPONENT/nuttx

	# NOTE - Don't put anything in here; we need the return value from 'make' below.

	# Check the return value from make, to determine if an error occurred during compilation.
	if [ $? != 0 ]; then
		# Something went wrong.
		echo -e "\n${RED}Compilation error.  Failed to build component $COMPONENT.\n${NO_COLOUR}"
		return 1
	fi

	# The compilation worked, so now just copy across the output binaries.
	mkdir -p $TCPATH/$OUTPUT_DIR/$COMPONENT
	$OBJCOPY -O binary $TCPATH/$TMP_SRC_DIR/$COMPONENT/nuttx/nuttx $TCPATH/$OUTPUT_DIR/${COMPONENT}/${COMPONENT_NAME}.bin

	# Check the return value from the object copy.
	if [ $? != 0 ]; then
		# Something went wrong.
		echo -e "\n${RED}Object copy error.  Failed to build component $COMPONENT.\n${NO_COLOUR}"			
		return 1
	fi
	echo -e ""

	# Also copy the ELF across, in case we also want that.
	cp $TCPATH/$TMP_SRC_DIR/$COMPONENT/nuttx/nuttx $TCPATH/$OUTPUT_DIR/${COMPONENT}/${COMPONENT_NAME}.elf

	# Print out details of the size of the generated ELF file (we do ELF instead of HEX since that yields more information).
	echo -e "${WHITE}Output file size details:${NO_COLOUR}"
	$SIZE --format=SysV --totals $TCPATH/$OUTPUT_DIR/${COMPONENT}/${COMPONENT_NAME}.elf	

	# All done.
	echo -e "${BOLD_WHITE}Build successful.  Output files written to $OUTPUT_DIR/$COMPONENT.\n${NO_COLOUR}"
	return 0
}

######################################## FUNCTION #########################################
###
### Name:		makenuttx_configure_apps
###
### Inputs/Outputs:	None
###
### Purpose:	Generates source code and configuration files for NuttX applications,
###				since the NuttX build system doesn't work with sources files in their
###				usual locations.  A separate NuttX application will be generated for each
###				executable in the component.
###
###########################################################################################

# NOTE - Because extended globbing is used inside this function, it needs to be enabled for the function DEFINITION as well.

# NOTE - Extended globbing is used here, but we turn it back off as soon as we are done, since it can plausibly break other things.

shopt -s extglob
makenuttx_configure_apps()
{
	# Check if the specified location is actually legit.
	if [ -z "$1" ] || [ ! -d $1 ]; then
		# The specified location is not a directory.
		echo -e "${RED}Invalid source location for configuring NuttX applications.\n${NO_COLOUR}"
		return 1
	fi

	# Create application configuration files for each executable.
	echo -e "${CYAN}\tConfiguring NuttX applications for:\n${NO_COLOUR}"
	echo -e "\n#\n# ValleyForge\n#" >> $1/nuttx/.config

	# TODO - Don't actually need to make a directory as such, because 'external' can just be a symlink.

	# Create a directory for ValleyForge applications. NuttX expects third party code in an 'external' directory: read the bottom of /apps/README.txt.
	mkdir $1/apps/external

	# Add the Kconfig entry for the new application directory so that 'make menuconfig' can find it.
	sed -i '6i\menu \"ValleyForge\"\nsource \"$APPSDIR/external/Kconfig\"\nendmenu\n' ${1}/apps/Kconfig

	# Restrict the scope of some variables used in the loop
	local APP_EXECUTABLES_ARRAY
	local APP_PRIORITIES_ARRAY
	local APP_STACKSIZE_ARRAY
	local APP_LOOP_MAX
	local C_SOURCE_FILES
	local ASSEMBLY_SOURCE_FILES
	local EXECUTABLE
	local MAIN_FILE

	APP_EXECUTABLES_ARRAY=($EXECUTABLES)
	APP_PRIORITIES_ARRAY=($PRIORITIES)	# TODO - Where does this come from?
	APP_STACKSIZE_ARRAY=($STACKSIZES)	# TODO - Where does this come from?
	APP_LOOP_MAX=$((${#APP_EXECUTABLES_ARRAY[@]}-1))

	# TODO - Why does this iteration happen separately?

	# Iterate over each of the executables and assign default configuration values to anything that isn't already assigned a value.
	for APP_INDEX in $(seq 0 $APP_LOOP_MAX)
	do
		APP_PRIORITIES_ARRAY[$APP_INDEX]=${APP_PRIORITIES_ARRAY[$APP_INDEX]:=$DEFAULT_APP_PRIORITY}
		APP_STACKSIZE_ARRAY[$APP_INDEX]=${APP_STACKSIZE_ARRAY[$APP_INDEX]:=$DEFAULT_APP_STACKSIZE}
	done

	# Iterate over each of the executables for this component.
	for APP_INDEX in $(seq 0 $APP_LOOP_MAX)
	do
		# Use a simpler variable name for readability.
		EXECUTABLE=${APP_EXECUTABLES_ARRAY[$APP_INDEX]}

		# For each executable, we'll need to build a separate application directory.
		echo -e "${CYAN}\t\tBuilding NuttX application code for: ${EXECUTABLE}.\n${NO_COLOUR}"

		# Create a directory for the application inside apps/external/.
		mkdir $1/apps/external/$EXECUTABLE

		# Copy the project application makefile and Kconfig files to the application directory.
		cp -f ${NUTTX_TEMPLATE_SOURCE}/Kconfig $1/apps/external/$EXECUTABLE/Kconfig
		cp -f ${NUTTX_TEMPLATE_SOURCE}/Makefile $1/apps/external/$EXECUTABLE/Makefile
		
		# Update the Kconfig file in apps/external to point to the Kconfig file for this application.
		echo "source \"\$APPSDIR/external/${EXECUTABLE}/Kconfig\"" >> $1/apps/external/Kconfig
		
		# Update the Make.defs file in apps/external to include the ValleyForge applications.
		echo "#ifeq (\$(CONFIG_VALLEYFORGE_${EXECUTABLE}),y)" >> $1/apps/external/Make.defs
		echo "CONFIGURED_APPS += external/${EXECUTABLE}" >> $1/apps/external/Make.defs
		echo "#endif" >> $1/apps/external/Make.defs

		# Enable the application by default.
		echo -e "CONFIG_VALLEYFORGE_${EXECUTABLE^^}=y" >> $1/nuttx/.config

		# TODO - This is a temporary solution.  Actually, should use symlinks, or use dependency detection to only copy those files required.

		# NOTE - Extended globbing is used here, but we turn it back off as soon as we are done, since it can plausibly break other things.

		# Copy the NuttX application files to the new application directory.
		shopt -s extglob
		cp -rf $1/!(apps|nuttx) $1/apps/external/$EXECUTABLE
		shopt -u extglob

		# TODO - Hopefully we don't need to do this retardedness forever.

		# NOTE - Extended globbing is used here, but we turn it back off as soon as we are done, since it can plausibly break other things.

		# Figure out what the main source file for this application is.
		shopt -s extglob nullglob
		MAIN_FILE=
		for F in $(ls $1/apps/external/${EXECUTABLE}/${EXECUTABLE}_main.@(c|cpp))
		do
			MAIN_FILE=${F#$1/apps/external/${EXECUTABLE}/}
			echo $MAIN_FILE
		done
		if [ -z "$MAIN_FILE" ]; then
			echo -e "${RED}\t\tUnabled to detect main source file for application.\n${NO_COLOUR}"
			return 1
		fi
		shopt -u extglob nullglob

		# Copy in the template Kconfig file and Makefile for the application.
		cp -f ${NUTTX_TEMPLATE_SOURCE}/Kconfig $1/apps/external/${EXECUTABLE}/Kconfig
		cp -f ${NUTTX_TEMPLATE_SOURCE}/Makefile $1/apps/external/${EXECUTABLE}/Makefile

		# Update the fields in the Kconfig file
		sed -i s^"<APP_NAME>"^"${EXECUTABLE}"^g $1/apps/external/${EXECUTABLE}/Kconfig
		sed -i s^"<APP_NAME_UPPER>"^"${EXECUTABLE^^}"^g $1/apps/external/${EXECUTABLE}/Kconfig

		# Update the fields in the Makefile
		sed -i s^"<APP_NAME>"^"${EXECUTABLE}"^g $1/apps/external/${EXECUTABLE}/Makefile
		sed -i s^"<APP_NAME_UPPER>"^"${EXECUTABLE^^}"^g $1/apps/external/${EXECUTABLE}/Makefile
		sed -i s^"<APP_PRIORITY>"^"${APP_PRIORITIES_ARRAY[$APP_INDEX]}"^g $1/apps/external/${EXECUTABLE}/Makefile		
		sed -i s^"<APP_STACK>"^"${APP_STACKSIZE_ARRAY[$APP_INDEX]}"^g $1/apps/external/${EXECUTABLE}/Makefile
		sed -i s^"<APP_MAIN>"^"${MAIN_FILE}"^g $1/apps/external/${EXECUTABLE}/Makefile

		# TODO - To be replaced with the toolchain's dependency detection functionality.

		# Find all the C and CPP files in the directory that aren't suffixed by "_main".
		C_SOURCE_FILES=($(find $1/apps/external/${EXECUTABLE} -iname "*.c" -o -iname "*.cpp" | grep -v "_main"))

		# Find all the assembly files in the directory.
		ASSEMBLY_SOURCE_FILES=($(find $1/apps/external -iname '*.s'))

		# Update the makefile with the source files
		sed -i s^"<C_SOURCE_FILES>"^"${C_SOURCE_FILES}"^g $1/apps/external/${EXECUTABLE}/Makefile
		sed -i s^"<ASSEMBLY_SOURCE_FILES>"^"${ASSEMBLY_SOURCE_FILES}"^g $1/apps/external/${EXECUTABLE}/Makefile

		# Enable the ValleyForge applications by default.
		echo -e "CONFIG_VALLEYFORGE_${EXECUTABLE^^}=y" >> $1/nuttx/.config

	done

	# All done.
	return 0
}
shopt -u extglob

# ALL DONE.
