#!/bin/bash

############################################################################################################################
### Name:		askForInfo											####
### Author:		Zac Frank											####
### Date Created:	21.11.11											####
### Type:		Bash Script											####
###															####
### Purpose:		This script gets called by uavstart, when the user's information has not been set.		####
###			It asks the user whether they want to set up their info, be reminded later, or to not set it	####
###			and never be reminded again.									####
############################################################################################################################

CYAN="\033[0;36m"
NO_COLOUR="\033[0m"
YELLOW="\033[1;33m"
RED="\033[0;31m"
BLUE="\033[0;34m"
UNDERLINED="\033[4m"
TCPATH="$1" 			# Import the ToolChain Path as a variable to be used.


echo -e "${YELLOW}It appears you have not yet entered the User Information used to create template files. Press" 
echo -e "\t${BLUE}${UNDERLINED}Y${NO_COLOUR}${YELLOW} to set this up now, \n\t${BLUE}${UNDERLINED}L${NO_COLOUR}${YELLOW} to be reminded later, or \n\t${BLUE}${UNDERLINED}N${NO_COLOUR}${YELLOW} to not bother and never be bothered about it again.\n${NO_COLOUR}"
    while :
    do
    read yorn								# await user input, should by y or n

	case "$yorn" in							# check value of $yorn. If value is...

	"Y"|"y")								# yes, then we...	    
	    bash $TCPATH/bld/Other/infoWrite $TCPATH				# run the infoWrite script, passing as a parameter the ToolChain Path
	    break								# escape the while loop as we have received a valid response.
	;;

	"N"|"n")								# no, then we...
	    sed -i "s/\(tc_startup *= *\).*/\1"no"/" $TCPATH/var/config.cfg		# change the value of startup in our config file
	    break								# escape the while loop as we have received a valid response.
	;;

	"L"|"l")								# no, then we...
	    echo -e "${YELLOW}\n You will be reminded in a most subtle manner about this next time you run uavstart\n${NO_COLOUR}"
	    sed -i "s/\(tc_startup *= *\).*/\1"later"/" $TCPATH/var/config.cfg			# change the value of startup in our config file
	    break								# escape the while loop as we have received a valid response.
	;;

	*)								# any other response
	    echo "${RED}You must choose a valid response..${NO_COLOUR}"			# the input is invalid, let's loop back.
	;;

	esac								# close case
    done	
   
# return to uavstart.