#!/bin/bash

###########################################################################################################################
###															###
### Name:		first_run											###
###															###
### Author:		Zac Frank											###
###															###
### Date Created:	15-11-2011											###
###															###
### Type:		Bash Script											###
###															###
### Purpose:		Prompts to user to enter their configuration information when the toolchain is first run.	###
###															###
###########################################################################################################################

# FIGURE OUT WHERE WE ARE.

# Determine what the absolute path to the root of the toolchain is.
SCRIPT=`readlink -f $0`
SCRIPTPATH=`dirname $SCRIPT`
TCPATH=$(echo $SCRIPTPATH | sed 's/\/bld.*//')

# DEFINE CONSTANTS.

# Define file names.

USER_CONFIG_FILE="var/config.cfg"
DEFAULT_USER_CONFIG_FILE="bld/default_user_config.cfg"
BUILD_CONFIG_FILE="bld/build_configs.cfg"

# Define the colours used for interface output.
source $TCPATH/bld/common/def_colours

################################ SCRIPT PROPER STARTS HERE ###############################

# Prompt the user to enter their name.
echo -e -n "${GREEN}Please enter your name: ${NO_COLOUR}"
read
echo -e ""

# Update the user name in the configuration file.
sed "s/tc_authname=.*/tc_authname=$REPLY/g" -i $TCPATH/$USER_CONFIG_FILE
echo -e "${CYAN}Changed username to $REPLY.\n${NO_COLOUR}"

# Create the lib and src directories.

mkdir $TCPATH/lib &>/dev/null
mkdir $TCPATH/src &>/dev/null


# Record that we've now completed the setup process.
sed "s/tc_startup=.*/tc_startup=done/g" -i $TCPATH/$USER_CONFIG_FILE

# All done.
exit 0

