#!/bin/bash

############################################################################################################################
### Name:		infoWrite											####
### Author:		Zac Frank											####
### Date Created:	21.11.11											####
### Type:		Bash Script											####
###															####
### Purpose:		This script gets called by askForInfo OR Edit, when the user chooses to edit their info.	####
###			It changes the string values of aspect and Author in the config.cfg file.			####
###															####
############################################################################################################################

CYAN="\033[0;36m"
NO_COLOUR="\033[0m"
YELLOW="\033[1;33m"
RED="\033[0;31m"
BLUE="\033[0;34m"
UNDERLINED="\033[4m"

TCPATH="$1" 			# Import the ToolChain Path as a variable to be used.

	    echo -e "${YELLOW}\nPlease enter your name:${NO_COLOUR}"
	    read authname
	    sed -i "s/\(tc_authname *= *\).*/\1$authname/" $TCPATH/var/config.cfg			# change the value of authname in our config file
	    echo -e "\n${YELLOW}Please describe which aspect of the UAV Project you are working on:${NO_COLOUR}"
	    read aspect
	    sed -i "s/\(tc_aspect *= *\).*/\1$aspect/" $TCPATH/var/config.cfg			# change the value of aspect in our config file
	    echo -e "${YELLOW}\n Thank you. That is all for now.\n${NO_COLOUR}"
	    sed -i "s/\(tc_startup *= *\).*/\1"set"/" $TCPATH/var/config.cfg			# change the value of startup in our config file

# Returns back from whence it came