#!/usr/bin/env bash

#	Copyright (C) 2012 Unison Networks Ltd
#
#	This program is free software: you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation, either version 3 of the License, or
#	(at your option) any later version.
#
#	This program is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with this program.  If not, see <http://www.gnu.org/licenses/>

###########################################################################################################################
###															###
### Name:		print_info_project										###
###															###
### Author:		Edwin Hayes											###
###															###
### Date Created:	05-04-2012											###
###															###
### Type:		Bash Script											###
###															###
### Purpose:		This script gets called by VFstart script, when the user chooses to view toolchain information.	###
###			It simply prints a summary of information about the toolchain to the console.			###
###															###
###########################################################################################################################

# FIGURE OUT WHERE WE ARE.

# MAKE SURE WE'RE IN A SANE ENVIRONMENT.

# Determine which operating system we are using.
VF_OS="$(uname)"
unset VF_OS_DARWIN
unset VF_OS_LINUX
if [ "${VF_OS}" == "Darwin" ]; then
	VF_OS_DARWIN=1
	VF_OSCFG_READLINK='greadlink'
	VF_OSCFG_SED='gsed'
	VF_OSCFG_SED_EXTPARAM='-E'
	VF_OSCFG_SED_INLPARAM='-i'
else
	VF_OS_LINUX=1
	VF_OSCFG_READLINK='readlink'
	VF_OSCFG_SED='sed'
	VF_OSCFG_SED_EXTPARAM='-r'
	VF_OSCFG_SED_INLPARAM='-i'
fi

# Check if we've got a sufficiently advanced version of BASH to actually run the toolchain.
if [[ ${BASH_VERSINFO[0]} < 4 ]]; then
	# BASH version before v4 are missing things we required, such as "read -i".
	echo -e "\033[0;31mBASH versions prior to 4.x are not supported.  Upgrade to a never version of BASH."
	exit 1
fi

# Check if all the tools we're expecting are installed.
VF_REQUIRED="${VF_OSCFG_READLINK} ${VF_OSCFG_SED}"
for VF_REQUIRED_ITEM in ${VF_REQUIRED}; do
	if [ -z "$(which ${VF_REQUIRED})" ]; then
		echo -e "\033[0;31mUnabled to find: ${VF_REQUIRED}.  Install this utility then try again."
		exit 1
	fi
done
unset VF_REQUIRED_ITEM
unset VF_REQUIRED

# Determine what the absolute path to the root of the toolchain is.
VF_SCRIPT=$(${VF_OSCFG_READLINK} -f $0)
VF_SCRIPTPATH=$(dirname $VF_SCRIPT)
TCPATH=$(echo $VF_SCRIPTPATH | ${VF_OSCFG_SED} 's/\/bld.*//')
unset VF_SCRIPTPATH
unset VF_SCRIPT

# DEFINE CONSTANTS.

# Define file names.

BUILD_CONFIG_FILE="bld/build_configs.cfg"

# Define the colours used for interface output.
source $TCPATH/bld/common/def_colours

# Create directories which don't come automatically with the toolchain.
source $TCPATH/bld/common/create_empty_dirs

##################################### MINOR FUNCTIONS ####################################

# Print a usage message.
usage()
{
	# Block-concatenate the message.
	cat << EOF

Usage: $0 [Options]

This script is used, as part of the 'Valley Forge' Embedded Toolchain to print toolchain information to the console.

Options:
	-h --help			Show this message.
EOF
	# All done.
	return 0
}

################################ SCRIPT PROPER STARTS HERE ###############################

# PARSE ANY COMMAND LINE PARAMETERS.

# Define variables required for 'getopt' to work.
PROGNAME=${0##*/} 
SHORTOPTS="h"
LONGOPTS="help"

# Use 'getopt' to parse the command line options.
ARGS=$(getopt -s bash --options $SHORTOPTS --longoptions $LONGOPTS --name $PROGNAME -- "$@")
eval set -- "$ARGS"

# Handle the parsed parameters.
while true; do
	# Select the appropriate behaviour for each parameter.
	case $1 in
		-h|--help)
			# Just print the usage message and then exit.
			usage
			exit 0
			;;
		--)
			# We're done parsing options.  We ignore anything else.
			shift
			break
			;;
		*)
			# We ignore anything else.
			shift
			break
			;;
	esac

	# Advance on to the next parameter.
	shift
done

# Parse the build configurations file.
source $TCPATH/bld/common/load_build_configs

# COLLECT TOOLCHAIN INFORMATION.

# TODO - This.  At least, figure out what build/revision/commit number/reference/tag this version of the toolchain is; then hence what it supports.

# PRINT TOOLCHAIN INFORMATION.

# Print a bit of a header.
echo -e "${BOLD_CYAN}TOOLCHAIN INFORMATION:\n${NO_COLOUR}"

# TODO - This.

# All done.
exit

