#!/usr/bin/env bash

TMP_CACHE=${TCPATH}/tmp/gen_cache/vendor/
#	Copyright (C) 2012 Unison Networks Ltd
#
#	This program is free software: you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation, either version 3 of the License, or
#	(at your option) any later version.
#
#	This program is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with this program.  If not, see <http://www.gnu.org/licenses/>

###########################################################################################################################
###															###
### Name:		setup_vendorcode										###
###															###
### Author:		Edwin Hayes											###
###															###
### Date Created:	26-02-2012											###
###															###
### Type:		Bash Script											###
###															###
### Purpose:		Provides functions which checks to see if a specific source of vendor code (code provided by a	###
###			external party) is available for use, and packs or unpacks it as required.  Typically, this	###
###			vendor code will be in the form of a git repository, and so the terms 'packs' and 'unpacks' are	###
###			somewhat misleading, because 'unpacking' actually entails downloading a copy of the source, and	###
###			'packing' involves deleting the downloaded files.						###
###															###
###########################################################################################################################

# Define the local and remote locations of the vendor sources.
VENDOR_MAVLINK_LOCAL=${TCPATH}/res/vendor/mavlink
VENDOR_MAVLINK_REMOTE="https://github.com/Aeronavics/mavlink.git"

VENDOR_FREERTOS_LOCAL=${TMP_CACHE}freertos
VENDOR_FREERTOS_REMOTE="http://sourceforge.net/projects/freertos/files/latest/download?source=files"

VENDOR_NUTTX_LOCAL=${TMP_CACHE}nuttx
VENDOR_NUTTX_REMOTE="git://git.code.sf.net/p/nuttx/git"

VENDOR_PIXHAWK_LOCAL=${TMP_CACHE}pixhawk
VENDOR_PIXHAWK_REMOTE="https://github.com/PX4/Firmware.git"

VENDOR_PIXHAWK_BOOTLOADER_LOCAL=${TMP_CACHE}pixhawk_bootloader
VENDOR_PIXHAWK_BOOTLOADER_REMOTE="https://github.com/PX4/Bootloader.git"

VENDOR_LM4TOOLS_LOCAL=${TMP_CACHE}lm4tools
VENDOR_LM4TOOLS_REMOTE="https://github.com/utzig/lm4tools.git"

VENDOR_STLINK_LOCAL=${TMP_CACHE}stlink
VENDOR_STLINK_REMOTE="https://github.com/texane/stlink.git"

VENDOR_ASTYLE_LOCAL=${TMP_CACHE}
VENDOR_ASTYLE_REMOTE="http://sourceforge.net/projects/astyle/files/latest/download?source=files"

VENDOR_UNCRUSTIFY_LOCAL=${TMP_CACHE}
VENDOR_UNCRUSTIFY_REMOTE="http://sourceforge.net/projects/uncrustify/files/latest/download?source=files"

VENDOR_PCREGREP_LOCAL=${TMP_CACHE}
VENDOR_PCREGREP_REMOTE="http://archive.ubuntu.com/ubuntu/pool/main/p/pcre3/pcre3_8.35.orig.tar.gz"

VENDOR_LIBUAVCAN_LOCAL=${TMP_CACHE}libuavcan
# VENDOR_LIBUAVCAN_REMOTE="https://github.com/UAVCAN/libuavcan.git"
VENDOR_LIBUAVCAN_REMOTE="https://github.com/Aeronavics/libuavcan.git"


VENDOR_LIBCANARD_LOCAL=${TMP_CACHE}libcanard
VENDOR_LIBCANARD_REMOTE="https://github.com/Aeronavics/libcanard.git"

VENDOR_LIBUAVCANSTM32_LOCAL=${TMP_CACHE}libuavcan_stm32
# VENDOR_LIBUAVCANSTM32_REMOTE="https://github.com/UAVCAN/libuavcan_stm32.git"
VENDOR_LIBUAVCANSTM32_REMOTE="https://github.com/Aeronavics/libuavcan_stm32.git"

VENDOR_UAVCAN_DSDL_LOCAL=${TMP_CACHE}dsdl
VENDOR_UAVCAN_DSDL_REMOTE="https://github.com/Aeronavics/DSDL.git"

VENDOR_UAVCAN_DSDL_CODE_GEN_LOCAL=${TMP_CACHE}dronecan_dsdlc
VENDOR_UAVCAN_DSDL_CODE_GEN_REMOTE="https://github.com/Aeronavics/dronecan_dsdlc.git"

VENDOR_JSON_LOCAL=${TMP_CACHE}nlohmann
VENDOR_JSON_REMOTE="https://github.com/nlohmann/json.git"

###########################################################################################
###                                                                                     ###
### NAME:              fetch_git_repository                                             ###
###                                                                                     ###
### Inputs:            $1 - Path to local sandpit.                                      ###
###                    $2 - Path (URL) to remote.                                       ###
###                    $3 - Identifier of branch or commit to checkout.  Else HEAD.     ###
###                                                                                     ###
### Outputs:           Zero for success, non-zero for failure.                          ###
###                                                                                     ###
### Purpose:           Checks out a Git repository, or if the repository has already    ###
###                    been checkout up, updates it to the specified commit.            ###
###                                                                                     ###
###########################################################################################

fetch_git_repository()
{
	# Alias the parameters for convenience.
	local GIT_LOCAL=$1
	local GIT_REMOTE=$2
	local GIT_BRANCH=$3

	# Check if the repository has been downloaded already
	if [ ! -d ${GIT_LOCAL} ]; then
		# We need to download the repository before we can use it
		echo -e "${CYAN}\tDownloading repository from ${GIT_REMOTE}...\n${NO_COLOUR}"
		git clone --depth=1 ${GIT_REMOTE} ${GIT_LOCAL}

		pushd ${GIT_LOCAL} >/dev/null
		git fetch origin +refs/heads/*:refs/remotes/origin/*
		echo -e ""
		popd >/dev/null

		# TODO - Check this actually worked.
	else
		# Check if the directory is not actually a git repository, which would indicate something bad.
		if [ ! -d ${GIT_LOCAL}/.git ]; then
			# The directory isn't a git repository, so something is very wrong.
			echo -e "${RED}The directory ${GIT_LOCAL} is not a git repository. Cannot fetch Git repository.\n${NO_COLOUR}"
			return 1
		else
			# The repository already exists, so just need to make sure it is up to date.
			echo -e "${CYAN}\tUpdating repository...\n${NO_COLOUR}"
			pushd ${GIT_LOCAL} >/dev/null
			git fetch origin +refs/heads/*:refs/remotes/origin/*
			echo -e ""
			popd >/dev/null

			# TODO - Check this actually worked.
		fi
	fi

	# Check out the specified branch/commit.
	if [ -z "${GIT_BRANCH}" ]; then
		GIT_BRANCH="origin/master"
	fi
	pushd ${GIT_LOCAL} >/dev/null
	git checkout ${GIT_BRANCH}
	local SUCCESS=$?
	echo -e ""
	popd >/dev/null

	# Check this actually worked.
	if [ "${SUCCESS}" == "0" ]; then
		echo -e "${CYAN}\tChecked out: ${GIT_BRANCH}.\n${NO_COLOUR}"
	else
		echo -e "${RED}\tFailed to check out: ${GIT_BRANCH}.\n${NO_COLOUR}"
		return 1
	fi

	# Update any git submodules
	echo -e "${CYAN}\tUpdating Git submodules...\n${NO_COLOUR}"
	pushd $GIT_LOCAL >/dev/null
	git submodule update --init --recursive --force
	echo -e ""
	popd >/dev/null

	# TODO - Check this actually worked.

	# All done.
	return 0
}

######################################## FUNCTION #########################################
###											###
### NAME:		unpack_mavlink							###
###											###
### Inputs/Outputs:	None.								###
###											###
### Purpose:		Checks if the MAVlink vendor source is available for use, and	###
###			if not, sets it up ready to go.					###
###											###
###########################################################################################

unpack_mavlink()
{
	# Fetch the mavlink git repository and make sure it's up to date.
	fetch_git_repository "${VENDOR_MAVLINK_LOCAL}" "${VENDOR_MAVLINK_REMOTE}" ${VF_VENDOR_MAVLINK_COMMITID-"origin/master"}

	# TODO - Test that now the required files actually exist.

	# All done.
	return 0
}

######################################## FUNCTION #########################################
###											###
### NAME:		unpack_freertos							###
###											###
### Inputs/Outputs:	None.								###
###											###
### Purpose:		Checks if the FreeRTOS vendor source is available for use, and	###
###			if not, sets it up ready to go.					###
###											###
###########################################################################################

unpack_freertos()
{
	# Check if the FreeRTOS source has been downloaded already.
	if [ ! -d ${VENDOR_FREERTOS_LOCAL} ]; then
		# We need to download and unpack the source before we can use it.
		echo -e "${CYAN}\tDownloading the FreeRTOS vendor source...\n${NO_COLOUR}"
		wget -O ${TMP_CACHE}/freertos_vendor.zip ${VENDOR_FREERTOS_REMOTE}
		unzip ${TMP_CACHE}/freertos_vendor.zip -d ${VENDOR_FREERTOS_LOCAL}
		if [ $? -ne 0 ]; then
			# We couldn't unzip the file, so something went wrong, and we abort.
			return 1
		fi
		echo -e ""

		# The newly unpacked directory will have some unhelpful nesting, so we flatten that.
		mv ${VENDOR_FREERTOS_LOCAL}/FreeRTOSV*/FreeRTOS/* ${VENDOR_FREERTOS_LOCAL}
		rm -rf ${VENDOR_FREERTOS_LOCAL}/FreeRTOSV*
	else
		# The source has already been downloaded.
		echo -e "${CYAN}\tFreeRTOS vendor source available...\n${NO_COLOUR}"

		# TODO - Maybe at some stage we might want to check if the existing files are up to date.
    	fi

	# TODO - Test that now the required files actually exist.

	# All done.
	return 0
}

######################################## FUNCTION #########################################
###											###
### NAME:		unpack_nuttx							###
###											###
### Inputs/Outputs:	None.								###
###											###
### Purpose:		Checks if the NuttX vendor source is available for use, and	###
###			if not, sets it up ready to go.					###
###											###
###########################################################################################

unpack_nuttx()
{
	# Fetch the NuttX git repository and make sure it's up to date.
	fetch_git_repository "${VENDOR_NUTTX_LOCAL}" "${VENDOR_NUTTX_REMOTE}" ${VF_VENDOR_NUTTX_COMMITID-"origin/master"}

	# Check for the existence of the key subfolders in the NuttX source. If they're missing, we can be confident that the download failed.
	if [ ! -d ${VENDOR_NUTTX_LOCAL}/nuttx ] && [ ! -d ${VENDOR_NUTTX_LOCAL}/apps ] && [ ! -d ${VENDOR_NUTTX_LOCAL}/misc ]; then
		echo -e "${RED}Unable to download the NuttX vendor source.\n${NO_COLOUR}"
		return 1
	fi

	# All done.
	return 0
}

######################################## FUNCTION #########################################
###											###
### NAME:		unpack_pixhawk							###
###											###
### Inputs/Outputs:	None.								###
###											###
### Purpose:		Checks if the Pixhawk vendor source is available for use, and	###
###			if not, sets it up ready to go.					###
###											###
###########################################################################################

unpack_pixhawk()
{
	# Fetch the Pixhawk git repository and make sure it's up to date.
	fetch_git_repository "${VENDOR_PIXHAWK_LOCAL}" "${VENDOR_PIXHAWK_REMOTE}" ${VF_VENDOR_PIXHAWK_COMMITID-"origin/master"}

	# Check for the existence of some folders from the Pixhawk source. If they're missing, we can be confident that the download failed.
	if [ ! -d ${VENDOR_PIXHAWK_LOCAL}/NuttX ] && [ ! -d ${VENDOR_PIXHAWK_LOCAL}/src ] && [ ! -d ${VENDOR_PIXHAWK_LOCAL}/makefiles ]; then
		echo -e "${RED}Unable to download the Pixhawk vendor source.\n${NO_COLOUR}"
		return 1
	fi

	# All done.
	return 0
}

######################################## FUNCTION #########################################
###                                                                                     ###
### NAME:		unpack_pixhawk_bootloader                                       ###
###                                                                                     ###
### Inputs/Outputs:	None.                                                           ###
###                                                                                     ###
### Purpose:		Checks if the Pixhawk bootloader vendor source is available for ###
###			use, and if not, sets it up ready to go.                        ###
###                                                                                     ###
###########################################################################################

unpack_pixhawk_bootloader()
{
	# Fetch the Pixhawk bootloader git repository and make sure it's up to date.
	fetch_git_repository "${VENDOR_PIXHAWK_BOOTLOADER_LOCAL}" "${VENDOR_PIXHAWK_BOOTLOADER_REMOTE}" ${VF_VENDOR_PIXHAWKBL_COMMITID-"origin/master"}

	# TODO - Test that now the required files actually exist.

	# All done.
	return 0
}

######################################## FUNCTION #########################################
###                                                                                     ###
### NAME:		unpack_lm4tools                                                 ###
###                                                                                     ###
### Inputs/Outputs:	None.                                                           ###
###                                                                                     ###
### Purpose:		Checks if the lm4tools vendor source is available for use, and	###
###			if not, sets it up ready to go.                                 ###
###                                                                                     ###
###########################################################################################

unpack_lm4tools()
{
	# Fetch the lm4tools git repository and make sure it's up to date.
	fetch_git_repository "${VENDOR_LM4TOOLS_LOCAL}" "${VENDOR_LM4TOOLS_REMOTE}" ${VF_VENDOR_LM4TOOLS_COMMITID-"origin/master"}

	# TODO - Test that now the required files actually exist.

	# All done.
	return 0
}

######################################## FUNCTION #########################################
###											###
### NAME:		unpack_vendor_stlink						###
###											###
### Inputs/Outputs:	None.								###
###											###
### Purpose:		Checks if the STlink vendor source is available for use, and	###
###			if not, sets it up ready to go.					###
###											###
###########################################################################################

unpack_vendor_stlink()
{
	# Fetch the stlink git repository and make sure it's up to date.
	fetch_git_repository "${VENDOR_STLINK_LOCAL}" "${VENDOR_STLINK_REMOTE}" ${VF_VENDOR_STLINK_COMMITID-"origin/master"}

	# TODO - Test that now the required files actually exist.

	# All done.
	return 0
}

######################################## FUNCTION #########################################
###
### Name:               unpack_vendor_astyle
###
### Inputs/Outputs:	None.
###
### Purpose:		Checks if astyle is available for use, and if not, sets it up ready
###					to go.
###
###########################################################################################

unpack_vendor_astyle()
{
	# Check if the astyle source has been downloaded already.
	if [ ! -d ${VENDOR_ASTYLE_LOCAL}/astyle ]; then
		# We need to download and unpack the source before we can use it.
		echo -e "${CYAN}\tDownloading the astyle vendor source...\n${NO_COLOUR}"
		wget -O ${TMP_CACHE}/astyle_vendor.tar.gz ${VENDOR_ASTYLE_REMOTE}
		tar -xzf ${TMP_CACHE}/astyle_vendor.tar.gz -C ${VENDOR_ASTYLE_LOCAL}
		if [ $? -ne 0 ]; then
			# We couldn't unzip the file, so something went wrong, and we abort.
			echo -e "\n${RED}ERROR - Failed to extract astyle_vendor.tar.gz\n${NO_COLOUR}"
			return 1
		fi
		echo -e ""

		# The newly unpacked directory will have some unhelpful nesting, so we flatten that.
		pushd "${VENDOR_ASTYLE_LOCAL}/astyle/build/gcc" >/dev/null
		make

		# NOTE - Don't put anything in here; we need the return value from 'make' below.

		# Check if making worked.
		if [ $? != 0 ]; then
			# Something went wrong.
			echo -e "\n${RED}ERROR - Failed to build AStyle.\n${NO_COLOUR}"
			popd >/dev/null
			return 1
		fi
		popd >/dev/null
	else
		# The source has already been downloaded.
		echo -e "${CYAN}\tAstyle available...\n${NO_COLOUR}"

		# TODO - Maybe should check if the files are up to date.
    fi

	# TODO - Test that now the required files actually exist.

	# All done.
	return 0
}

######################################## FUNCTION #########################################
###											###
### NAME:		unpack_vendor_uncrustify					###
###											###
### Inputs/Outputs:	None.								###
###											###
### Purpose:		Checks if uncrustify is available for use, and			###
###			if not, sets it up ready to go.					###
###											###
###########################################################################################

unpack_vendor_uncrustify()
{
	# Check if the uncrustify source has been downloaded already.
	if [ ! -d ${VENDOR_UNCRUSTIFY_LOCAL}/uncrustify* ]; then
		# We need to download and unpack the source before we can use it.
		echo -e "${CYAN}\tDownloading the Uncrustify vendor source...\n${NO_COLOUR}"
		wget -O ${TMP_CACHE}/uncrustify_vendor.tar.gz ${VENDOR_UNCRUSTIFY_REMOTE}
		tar -xzf ${TMP_CACHE}/uncrustify_vendor.tar.gz -C ${VENDOR_UNCRUSTIFY_LOCAL}
		if [ $? -ne 0 ]; then
			# We couldn't unzip the file, so something went wrong, and we abort.
			echo -e "\n${RED}ERROR - Failed to extract uncrustify_vendor.tar.gz\n${NO_COLOUR}"
			return 1
		fi
		echo -e ""

		pushd ${VENDOR_UNCRUSTIFY_LOCAL}/uncrustify* >/dev/null
		${VENDOR_UNCRUSTIFY_LOCAL}/uncrustify*/configure

		# Check if configuring worked.
		if [ $? != 0 ]; then
			# Something went wrong.
			echo -e "\n${RED}ERROR - Failed to build Uncrustify: the 'configure' stage failed.\n${NO_COLOUR}"
			popd >/dev/null
			return 1
		fi
		# Then we make.
		make

		# NOTE - Don't put anything in here; we need the return value from 'make' below.

		# Check if making worked.
		if [ $? != 0 ]; then
			# Something went wrong.
			echo -e "\n${RED}ERROR - Failed to build Uncrustify: the 'make' stage failed.\n${NO_COLOUR}"
			popd >/dev/null
			return 1
		fi
		popd >/dev/null

		# Probably need a new line to keep things tidy.
		echo ""
	else
		# The source has already been downloaded.
		echo -e "${CYAN}\tUncrustify available...\n${NO_COLOUR}"

		# TODO - Maybe should check if the existing files are up to date.
    fi

	# TODO - Test that now the required files actually exist.

	# All done.
	return 0
}

######################################## FUNCTION #########################################
###											###
### NAME:		unpack_vendor_pcregrep						###
###											###
### Inputs/Outputs:	None.								###
###											###
### Purpose:		Checks if uncrustify is available for use, and			###
###			if not, sets it up ready to go.					###
###											###
###########################################################################################

unpack_vendor_pcregrep()
{
	# Check if pcregrep has been downloaded already.
	if [ ! -d ${VENDOR_PCREGREP_LOCAL}/pcre-8.35 ]; then
		# We need to download and unpack the source before we can use it.
		echo -e "${CYAN}\tDownloading pcregrep...\n${NO_COLOUR}"
		wget -O ${TMP_CACHE}/pcre_vendor.tar.gz ${VENDOR_PCREGREP_REMOTE}
		tar -xzf ${TMP_CACHE}/pcre_vendor.tar.gz -C ${VENDOR_PCREGREP_LOCAL}
		if [ $? -ne 0 ]; then
			# We couldn't unzip the file, so something went wrong, and we abort.
			echo -e "\n${RED}ERROR - Failed to extract pcre_vendor.tar.gz\n${NO_COLOUR}"
			return 1
		fi
		echo -e ""

		pushd ${VENDOR_PCREGREP_LOCAL}/pcre-8.35 >/dev/null
		${VENDOR_PCREGREP_LOCAL}/pcre-8.35/configure

		# Check if configuring worked.
		if [ $? != 0 ]; then
			# Something went wrong.
			echo -e "\n${RED}ERROR - Failed to build Pcregrep: the 'configure' stage failed.\n${NO_COLOUR}"
			popd >/dev/null
			return 1
		fi
		# Then we make.
		make

		# NOTE - Don't put anything in here; we need the return value from 'make' below.

		# Check if making worked.
		if [ $? != 0 ]; then
			# Something went wrong.
			echo -e "\n${RED}ERROR - Failed to build Pcregrep: the 'make' stage failed.\n${NO_COLOUR}"
			popd >/dev/null
			return 1
		fi
		popd >/dev/null

		# Probably need a new line to keep things tidy.
		echo ""
	else
		# The source has already been downloaded.
		echo -e "${CYAN}\tPcregrep available...\n${NO_COLOUR}"

		# TODO - Maybe should check if the existing files are up to date.
    fi

	# TODO - Test that now the required files actually exist.

	# All done.
	return 0
}

######################################## FUNCTION #########################################
###											###
### NAME:		pack_allv							###
###											###
### Inputs/Outputs:	None.								###
###											###
### Purpose:		For each vendor source which was previously unpacked, packs	###
###			those sources back again.					###
###											###
###########################################################################################

pack_allv()
{
	# Just pack each of the vendor sources in turn.
	pack_mavlink
	pack_freertos
	pack_vendor_nuttx
	pack_vendor_lm4tools
	pack_vendor_stlink
	pack_vendor_astyle
	pack_vendor_uncrustify
	pack_vendor_pcregrep
}

######################################## FUNCTION #########################################
###											###
### NAME:		pack_mavlink							###
###											###
### Inputs/Outputs:	None.								###
###											###
### Purpose:		Checks if the MAVlink vendor source was previously unpacked,	###
###			and if it was, then packs it back up again.			###
###											###
###########################################################################################

pack_mavlink()
{
	# Check if the MAVlink repository has been downloaded already.
	if [ -d ${VENDOR_MAVLINK_LOCAL} ]; then
		# We just delete the downloaded clone of the repository.
		echo -e "${CYAN}\tCleaning up MAVlink vendor source...\n${NO_COLOUR}"
		rm -Rf ${VENDOR_MAVLINK_LOCAL}
    	fi
		# Else, the source is already packed.

	# All done.
	return
}

######################################## FUNCTION #########################################
###											###
### NAME:		pack_freertos							###
###											###
### Inputs/Outputs:	None.								###
###											###
### Purpose:		Checks if the FreeRTOS vendor source was previously unpacked,	###
###			and if it was, then packs it back up again.			###
###											###
###########################################################################################

pack_freertos()
{
	# Check if the FreeRTOS repository has been downloaded already.
	if [ -d ${VENDOR_FREERTOS_LOCAL} ]; then
		# We just delete the downloaded clone of the repository.
		echo -e "${CYAN}\tCleaning up FreeRTOS vendor source...\n${NO_COLOUR}"
		rm -Rf ${VENDOR_FREERTOS_LOCAL}
    	fi
		# Else, the source is already packed.

	# All done.
	return
}

######################################## FUNCTION #########################################
###											###
### NAME:		pack_nuttx							###
###											###
### Inputs/Outputs:	None.								###
###											###
### Purpose:		Checks if the NuttX vendor source was previously unpacked,	###
###			and if it was, then packs it back up again.			###
###											###
###########################################################################################

pack_vendor_nuttx()
{
	# Check if the NuttX repository has been downloaded already.
	if [ -d ${VENDOR_NUTTX_LOCAL} ]; then
		# We just delete the downloaded clone of the repository.
		echo -e "${CYAN}\tCleaning up the NuttX vendor source...\n${NO_COLOUR}"
		rm -Rf ${VENDOR_NUTTX_LOCAL}
	fi
	# Else, the source is already packed.

	# All done.
	return
}

######################################## FUNCTION #########################################
###											###
### NAME:			pack_vendor_lm4tools					###
###											###
### Inputs/Outputs:	None.								###
###											###
### Purpose:		Checks if the lm4tools vendor source was previously unpacked,	###
###			and if it was, then packs it back up again.			###
###											###
###########################################################################################

pack_vendor_lm4tools()
{
	# Check if the lm4tools repository has been downloaded already.
	if [ -d ${VENDOR_LM4TOOLS_LOCAL} ]; then
		# We just delete the downloaded clone of the repository.
		echo -e "${CYAN}\tCleaning up lm4tools vendor source...\n${NO_COLOUR}"
		rm -Rf ${VENDOR_LM4TOOLS_LOCAL}
    	fi
		# Else, the source is already packed.

	# All done.
	return
}

######################################## FUNCTION #########################################
###											###
### NAME:		pack_vendor_stlink						###
###											###
### Inputs/Outputs:	None.								###
###											###
### Purpose:		Checks if the STLink vendor source was previously unpacked,	###
###			and if it was, then packs it back up again.			###
###											###
###########################################################################################

pack_vendor_stlink()
{
	# Check if the STLink repository has been downloaded already.
	if [ -d ${VENDOR_STLINK_LOCAL} ]; then
		# We just delete the downloaded clone of the repository.
		echo -e "${CYAN}\tCleaning up STLink vendor source...\n${NO_COLOUR}"
		rm -Rf ${VENDOR_STLINK_LOCAL}
    	fi
		# Else, the source is already packed.

	# All done.
	return
}

######################################## FUNCTION #########################################
###											###
### NAME:		pack_vendor_astyle						###
###											###
### Inputs/Outputs:	None.								###
###											###
### Purpose:		Checks if astyle was previously unpacked,			###
###			and if it was, then packs it back up again.			###
###											###
###########################################################################################

pack_vendor_astyle()
{
	# Check if astyle source has been downloaded already.
	if [ -d ${VENDOR_ASTYLE_LOCAL} ]; then
		# We just delete the downloaded tar file and source files of astyle.
		echo -e "${CYAN}\tCleaning up Astyle source...\n${NO_COLOUR}"
		rm -Rf ${VENDOR_ASTYLE_LOCAL}/astyle
		rm ${TMP_CACHE}/astyle_vendor.tar.gz
    	fi
		# Else, the source is already packed.

	# All done.
	return
}

######################################## FUNCTION #########################################
###											###
### NAME:		pack_vendor_uncrustify						###
###											###
### Inputs/Outputs:	None.								###
###											###
### Purpose:		Checks if uncrustify was previously unpacked,			###
###			and if it was, then packs it back up again.			###
###											###
###########################################################################################

pack_vendor_uncrustify()
{
	# Check if uncrustify source has been downloaded already.
	if [ -d ${VENDOR_UNCRUSTIFY_LOCAL} ]; then
		# We just delete the downloaded tar file and source files of uncrustify.
		echo -e "${CYAN}\tCleaning up Uncrustify source...\n${NO_COLOUR}"
		rm -Rf ${VENDOR_UNCRUSTIFY_LOCAL}/uncrustify*
		rm ${TMP_CACHE}/uncrustify_vendor.tar.gz
    	fi
		# Else, the source is already packed.

	# All done.
	return
}

######################################## FUNCTION #########################################
###											###
### NAME:		pack_vendor_pcregrep						###
###											###
### Inputs/Outputs:	None.								###
###											###
### Purpose:		Checks if pcregrep was previously unpacked,			###
###			and if it was, then packs it back up again.			###
###											###
###########################################################################################

pack_vendor_pcregrep()
{
	# Check if pcregrep has been downloaded already.
	if [ -d ${VENDOR_PCREGREP_LOCAL} ]; then
		# We just delete the downloaded tar file and source files of pcregrep.
		echo -e "${CYAN}\tCleaning up pcregrep source...\n${NO_COLOUR}"
		rm -Rf ${VENDOR_PCREGREP_LOCAL}/pcre-8.35
		rm ${TMP_CACHE}/pcregrep_vendor.tar.gz
    	fi
		# Else, the source is already packed.

	# All done.
	return
}

######################################## FUNCTION #########################################
###											###
### NAME:		unpack_libuavcan						###
###											###
### Inputs/Outputs:	None.								###
###											###
### Purpose:		Checks if the libuavcan vendor source is available for use, and	###
###			if not, sets it up ready to go.					###
###											###
###########################################################################################

unpack_libuavcan()
{
	# Fetch the libuavcan git repository and make sure it's up to date.
	fetch_git_repository "${VENDOR_LIBUAVCAN_LOCAL}" "${VENDOR_LIBUAVCAN_REMOTE}" ${VF_VENDOR_LIBUAVCAN_BRANCH-"origin/master"}

	# TODO - Test that now the required files actually exist.

	# All done.
	return 0
}

######################################## FUNCTION #########################################
###											###
### NAME:		pack_libuavcan							###
###											###
### Inputs/Outputs:	None.								###
###											###
### Purpose:		Checks if the libuavcan vendor source was previously unpacked,	###
###			and if it was, then packs it back up again.			###
###											###
###########################################################################################

pack_libuavcan()
{
	# Check if the libuavcan repository has been downloaded already.
	if [ -d ${VENDOR_LIBUAVCAN_LOCAL} ]; then
		# We just delete the downloaded clone of the repository.
		echo -e "${CYAN}\tCleaning up libuavcan vendor source...\n${NO_COLOUR}"
		rm -Rf ${VENDOR_LIBUAVCAN_LOCAL}
    	fi
		# Else, the source is already packed.

	# All done.
	return
}


######################################## FUNCTION #########################################
###											###
### NAME:		unpack_libcanard						###
###											###
### Inputs/Outputs:	None.								###
###											###
### Purpose:		Checks if the libuavcan vendor source is available for use, and	###
###			if not, sets it up ready to go.					###
###											###
###########################################################################################

unpack_libcanard()
{
	# Fetch the libcanard git repository and make sure it's up to date.
        fetch_git_repository "${VENDOR_LIBCANARD_LOCAL}" "${VENDOR_LIBCANARD_REMOTE}" ${VF_VENDOR_LIBCANARD_BRANCH-"origin/master"}
	# TODO - Test that now the required files actually exist.

	# All done.
	return 0
}

######################################## FUNCTION #########################################
###											###
### NAME:		pack_libcanard							###
###											###
### Inputs/Outputs:	None.								###
###											###
### Purpose:		Checks if the libuavcan vendor source was previously unpacked,	###
###			and if it was, then packs it back up again.			###
###											###
###########################################################################################

pack_libcanard()
{
	# Check if the libuavcan repository has been downloaded already.
	if [ -d ${VENDOR_LIBCANARD_LOCAL} ]; then
		# We just delete the downloaded clone of the repository.
		echo -e "${CYAN}\tCleaning up libcanard vendor source...\n${NO_COLOUR}"
		rm -Rf ${VENDOR_LIBCANARD_LOCAL}
    	fi
		# Else, the source is already packed.

	# All done.
	return
}

######################################## FUNCTION #########################################
###											###
### NAME:		unpack_libcanard						###
###											###
### Inputs/Outputs:	None.								###
###											###
### Purpose:		Checks if the libuavcan vendor source is available for use, and	###
###			if not, sets it up ready to go.					###
###											###
###########################################################################################

unpack_libuavcan_stm32()
{
	# Fetch the libcanard git repository and make sure it's up to date.
        fetch_git_repository "${VENDOR_LIBUAVCANSTM32_LOCAL}" "${VENDOR_LIBUAVCANSTM32_REMOTE}" HEAD
	# TODO - Test that now the required files actually exist.

	# All done.
	return 0
}

######################################## FUNCTION #########################################
###											###
### NAME:		pack_libcanard							###
###											###
### Inputs/Outputs:	None.								###
###											###
### Purpose:		Checks if the libuavcan vendor source was previously unpacked,	###
###			and if it was, then packs it back up again.			###
###											###
###########################################################################################

pack_libuavcan_stm32()
{
	# Check if the libuavcan repository has been downloaded already.
	if [ -d ${VENDOR_LIBUAVCANSTM32_LOCAL} ]; then
		# We just delete the downloaded clone of the repository.
		echo -e "${CYAN}\tCleaning up libuavcan_stm32 vendor source...\n${NO_COLOUR}"
		rm -Rf ${VENDOR_LIBUAVCANSTM32_LOCAL}
    	fi
		# Else, the source is already packed.

	# All done.
	return
}

######################################## FUNCTION #########################################
###											###
### NAME:		unpack_uavcan_dsdl						###
###											###
### Inputs/Outputs:	None.								###
###											###
### Purpose:		Checks if the dsdl vendor source is available for use, and	###
###			if not, sets it up ready to go.					###
###											###
###########################################################################################

unpack_uavcan_dsdl()
{
	# Fetch the libcanard git repository and make sure it's up to date.
        fetch_git_repository "${VENDOR_UAVCAN_DSDL_LOCAL}" "${VENDOR_UAVCAN_DSDL_REMOTE}" ${VF_VENDOR_DSDL_BRANCH-"origin/master"}
	# TODO - Test that now the required files actually exist.

	# All done.
	return 0
}

######################################## FUNCTION #########################################
###											###
### NAME:		pack_uavcan_dsdl							###
###											###
### Inputs/Outputs:	None.								###
###											###
### Purpose:		Checks if the pack_uavcan_dsdl vendor source was previously unpacked,	###
###			and if it was, then packs it back up again.			###
###											###
###########################################################################################

pack_uavcan_dsdl()
{
	# Check if the libuavcan repository has been downloaded already.
	if [ -d ${VENDOR_UAVCAN_DSDL_LOCAL} ]; then
		# We just delete the downloaded clone of the repository.
		echo -e "${CYAN}\tCleaning up uavcan_dsdl vendor source...\n${NO_COLOUR}"
		rm -Rf ${VENDOR_UAVCAN_DSDL_LOCAL}
    	fi
		# Else, the source is already packed.

	# All done.
	return
}

######################################## FUNCTION #########################################
###											###
### NAME:		unpack_uavcan_dsdl_code_gen						###
###											###
### Inputs/Outputs:	None.								###
###											###
### Purpose:		Checks if the dsdl code generator vendor source is available for use, and	###
###			if not, sets it up ready to go.					###
###											###
###########################################################################################

unpack_uavcan_dsdl_code_gen()
{
	# Fetch the libcanard git repository and make sure it's up to date.
        fetch_git_repository "${VENDOR_UAVCAN_DSDL_CODE_GEN_LOCAL}" "${VENDOR_UAVCAN_DSDL_CODE_GEN_REMOTE}" ${VF_VENDOR_DSDL_GEN_BRANCH-"origin/master"}
	# TODO - Test that now the required files actually exist.

	# All done.
	return 0
}

######################################## FUNCTION #########################################
###											###
### NAME:		pack_uavcan_dsdl							###
###											###
### Inputs/Outputs:	None.								###
###											###
### Purpose:		Checks if the pack_uavcan_dsdl vendor source was previously unpacked,	###
###			and if it was, then packs it back up again.			###
###											###
###########################################################################################

pack_uavcan_dsdl_code_gen()
{
	# Check if the libuavcan repository has been downloaded already.
	if [ -d ${VENDOR_UAVCAN_DSDL_CODE_GEN_LOCAL} ]; then
		# We just delete the downloaded clone of the repository.
		echo -e "${CYAN}\tCleaning up uavcan_dsdl vendor source...\n${NO_COLOUR}"
		rm -Rf ${VENDOR_UAVCAN_DSDL_CODE_GEN_LOCAL}
    	fi
		# Else, the source is already packed.

	# All done.
	return
}

# ALL DONE.

######################################## FUNCTION #########################################
###											###
### NAME:		unpack_uavcan_dsdl_code_gen						###
###											###
### Inputs/Outputs:	None.								###
###											###
### Purpose:		Checks if the dsdl code generator vendor source is available for use, and	###
###			if not, sets it up ready to go.					###
###											###
###########################################################################################

unpack_json()
{
	# Fetch the libcanard git repository and make sure it's up to date.
        fetch_git_repository "${VENDOR_JSON_LOCAL}" "${VENDOR_JSON_REMOTE}" ${VF_VENDOR_JSON_BRANCH-"origin/master"}
	# TODO - Test that now the required files actually exist.

	# All done.
	return 0
}

######################################## FUNCTION #########################################
###											###
### NAME:		pack_uavcan_dsdl							###
###											###
### Inputs/Outputs:	None.								###
###											###
### Purpose:		Checks if the pack_uavcan_dsdl vendor source was previously unpacked,	###
###			and if it was, then packs it back up again.			###
###											###
###########################################################################################

pack_json()
{
	# Check if the libuavcan repository has been downloaded already.
	if [ -d ${VENDOR_JSON_LOCAL} ]; then
		# We just delete the downloaded clone of the repository.
		echo -e "${CYAN}\tCleaning up json vendor source...\n${NO_COLOUR}"
		rm -Rf ${VENDOR_JSON_LOCAL}
    	fi
		# Else, the source is already packed.

	# All done.
	return
}

# ALL DONE.
