#!/bin/bash

# For the moment, we just print out a message to the user.
echo -e "${GREEN}This is some kind of prompt...\n${NO_COLOUR}"

# Create a separate section in the component configuration file for target specific stuff.
echo -e "### TARGET SPECIFIC ###\n" >> $TCPATH/src/$COMPONENT/$COMPONENT.cfg

# Write configuration settings to the configuration file.
echo -e "LOLLIPOP='Sunshine!'" >> $TCPATH/src/$COMPONENT/$COMPONENT.cfg
echo -e "RAINBOW='Bright!'" >> $TCPATH/src/$COMPONENT/$COMPONENT.cfg
echo -e "" >> $TCPATH/src/$COMPONENT/$COMPONENT.cfg

