#!/bin/bash

#	Copyright (C) 2011  Unison Networks Ltd
#
#	This program is free software: you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation, either version 3 of the License, or
#	(at your option) any later version.
#
#	This program is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with this program.  If not, see <http://www.gnu.org/licenses/>.

# For the moment, we just print out a message to the user.
echo -e "${YELLOW}No target specific configuration required...\n${NO_COLOUR}"

# Create a separate section in the component configuration file for target specific stuff.
echo -e "### TARGET SPECIFIC ###\n" >> $TCPATH/src/$COMPONENT/$COMPONENT.cfg

# Write configuration settings to the configuration file.
echo -e "LOLLIPOP='Sunshine!'" >> $TCPATH/src/$COMPONENT/$COMPONENT.cfg
echo -e "RAINBOW='Bright!'" >> $TCPATH/src/$COMPONENT/$COMPONENT.cfg
echo -e "" >> $TCPATH/src/$COMPONENT/$COMPONENT.cfg

# All done.

