#!/bin/bash

# For the moment, we just print out a message to the user.
echo -e "${GREEN}This is some other kind of prompt...\n${NO_COLOUR}"

# Create a separate section in the component configuration file for target specific stuff.
echo -e "### BOOTLOADER SPECIFIC ###\n" >> $TCPATH/src/$COMPONENT/$COMPONENT.cfg

# Write configuration settings to the configuration file.
echo -e "PUPPIES='Woof!'" >> $TCPATH/src/$COMPONENT/$COMPONENT.cfg
echo -e "KITTENS='Meow!'" >> $TCPATH/src/$COMPONENT/$COMPONENT.cfg
echo -e "" >> $TCPATH/src/$COMPONENT/$COMPONENT.cfg
