#!/bin/bash

#	Copyright (C) 2011 Unison Networks Ltd
#
#	This program is free software: you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation, either version 3 of the License, or
#	(at your option) any later version.
#
#	This program is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with this program.  If not, see <http://www.gnu.org/licenses/>

###########################################################################################################################
###
### Name:           checkfuncs_layout_whitespace
###
### Author:         Ravi Shankar
###
### Date Created:	13-01-2015
###
### Type:           Bash Function Definitions
###
### Purpose:        Implements code compliance tests: tests for proper layout conventions(whitespace) in files.
###
###########################################################################################################################

######################################## FUNCTION #########################################
###
### Name:		compliance_check_file_layout_whitespace
###
### Inputs/Outputs:	Path to the file to test.
###
### Purpose:	Tests a single C/CPP source file for proper layout conventions(whitespace).
###
###########################################################################################


compliance_check_file_layout_whitespace()
{
	# The file we're checking was the first argument we received.
	local FILE=$1

	#Run "Artistic Style" with the file as its input and store the output string with status of the operation.
	str=$(astyle --style=allman -p -k1 --dry-run $FILE) 
	status=${str%% *}
		
	#Condition to check the status of the operation(Formatted - changes present, Unchanged - no changes required)
	if [[ "$status" == "Formatted" ]]; then
		compliance_fail_file "compliance_check_file_layout_whitespace" $FILE "This file doesn't follow proper layout conventions(whitespace)"
	fi

	return 0
}

######################################## FUNCTION #########################################
###
### Name:		compliance_get_rules_layout_whitespace
###
### Inputs/Outputs:	None.
###
### Purpose:	Prints out a summary of the code compliance rules for the "layout_whitespace" test.
###
###########################################################################################

compliance_get_rules_layout_whitespace()
{
	echo "Layout conventions(whitespace):"
	echo "\tAll C++ anc C files should follow proper layout conventions(whitespace)."
	echo "\tUnary operators do not require surrounding whitespace."
	echo "\tBinary operators should be surrounded by single space characters."
	echo "\tTernary operators should be surrounded by single space characters. This includes the characters separating the two latter arguments."
	echo "\tC++ reserved words should be followed by a single space character."
	echo "\tCommas should be followed by a space character."
	echo "\tSemi-colons in a 'for' statement should be followed by a single space character."
	echo "\tAssignment operators should be surrounded by single space characters."
	echo "\tWhen used in the declaration of a veriable of type 'pointer' or 'reference', the relevant operators are to be placed against the type of declaration, not the name of the variable."
	echo "\tParantheses do not require surroundign white-space."
	echo "\tAngle braces used for template declarations do not require surrounding white-space."
	echo ""
}

# ALL DONE.
