#!/bin/bash

#	Copyright (C) 2011 Unison Networks Ltd
#
#	This program is free software: you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation, either version 3 of the License, or
#	(at your option) any later version.
#
#	This program is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with this program.  If not, see <http://www.gnu.org/licenses/>

###########################################################################################################################
###
### Name:           checkfuncs_comment
###
### Author:         Ravi Shankar
###
### Date Created:	13-01-2015
###
### Type:           Bash Function Definitions
###
### Purpose:        Implements code compliance tests: tests for proper commenting conventions in files.
###
###########################################################################################################################

######################################## FUNCTION #########################################
###
### Name:		compliance_check_file_comment
###
### Inputs/Outputs:	Path to the file to test.
###
### Purpose:	Tests a single C/CPP source file for proper commenting conventions.
###
###########################################################################################

compliance_check_file_comment()
{
	# The file we're checking was the first argument we received.
	local FILE=$1

	# If we encounter something wrong, then we make a note that there is at least some kind of issue with the file as a whole.
	local CHECKS_OK=1

	#Condition to check if the file has multiple C++ comments.
	if pcregrep -q -M '(\/\/+(.*))+(\n([\/\/]+(.*))+)+' $1; then
		CHECKS_OK=
	fi

	#Condition to check if the file has single line C style("/* .... */") comments.
	if pcregrep -q -M '\/+\*+(.*)\*\/+' $1; then
		CHECKS_OK=
	fi

	if [ ! ${CHECKS_OK} ]; then
		# Report that the file has failed.
		compliance_fail_file "compliance_check_file_layout_comment" $1 "This file contains non-compliant comment(s)."
	fi

	return 0
}

######################################## FUNCTION #########################################
###
### Name:		compliance_get_rules_comment
###
### Inputs/Outputs:	None.
###
### Purpose:	Prints out a summary of the code compliance rules for the comment test.
###
###########################################################################################

compliance_get_rules_comment()
{
	echo "Commenting conventions:"
	echo "\tAll C++ anc C files should follow proper commenting conventions."
	echo "\tMultiple comment lines should be in C style(/* ... */) and single comment lines should be in C++ style(// ....)"
	echo ""
}

# ALL DONE.
