#!/usr/bin/env bash

#	Copyright (C) 2011 Unison Networks Ltd
#
#	This program is free software: you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation, either version 3 of the License, or
#	(at your option) any later version.
#
#	This program is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with this program.  If not, see <http://www.gnu.org/licenses/>

###########################################################################################################################
###
### Name:           	checkfuncs_layout
###
### Author:         	Ravi Shankar
###
### Date Created:	13-01-2015
###
### Type:           	Bash Function Definitions
###
### Purpose:        	Implements code compliance tests: tests for proper layout conventions in files.
###
###########################################################################################################################

######################################## FUNCTION ##################################################
###
### Name:		compliance_check_file_layout
###
### Inputs/Outputs:	Path to the file to test.
###
### Purpose:		Tests a single C/CPP source file for proper layout conventions.
###
####################################################################################################


compliance_check_file_layout()
{
	# The file we're checking was the first argument we received.
	local FILE=$1

	# Variable to store the output from running AStyle.
	local status=

	# Run "Artistic Style" with the given file and store the output string with status of the operation. 
	str=$($TCPATH/res/vendor/astyle/build/gcc/bin/astyle --style=allman -t -C -S -N -p -k1 -U -H -xy -j --dry-run $FILE) 			
	status=${str%% *}

	# Condition to check the status of the operation(Formatted - changes present, Unchanged - no changes required)
	if [[ "$status" == "Formatted" ]]; then

		# Report that the file has failed.
		compliance_fail_file "compliance_check_file_layout" $FILE "This file doesn't follow proper layout conventions"
	fi

	# All done.
	return 0
}

# ALL DONE.
