#!/bin/bash

#	Copyright (C) 2011 Unison Networks Ltd
#
#	This program is free software: you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation, either version 3 of the License, or
#	(at your option) any later version.
#
#	This program is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with this program.  If not, see <http://www.gnu.org/licenses/>

###########################################################################################################################
###
### Name:           	checkfuncs_headercheck
###
### Author:         	Ravi Shankar
###
### Date Created:	08-01-2015
###
### Type:           	Bash Function Definitions
###
### Purpose:        	Implements code compliance tests: tests for corresponding header files.
###
###########################################################################################################################

######################################## FUNCTION #########################################
###
### Name:		compliance_check_file_headercheck
###
### Inputs/Outputs:	Path to the file to test.
###
### Purpose:		Tests a single C/CPP source file for a matching header file.
###
###########################################################################################

compliance_check_file_headercheck()
{
	# The file we're checking was the first argument we received.
	local FILE=$1

	# Extract the filename from the entire path
	filename_ext=$(basename "$FILE")

	# Extract the directory where the file resides.
	file_directory=${FILE%/*}

	# Condition to check if the file is a "C++" or "C" file.
	if [[ $filename_ext =~ ".cpp" || $filename_ext =~ ".c" ]]; then
		
		# Extract the filename alone without the extension
		filename="${filename_ext%.*}"

		# Condition to match C++ file
		if [[ $filename_ext =~ ".cpp" ]]; then
			headerfile=$filename".hpp"

		# Condition to match C file
		elif [[ $filename_ext =~ ".c" ]]; then
			headerfile=$filename".h"
		fi
		
		# Condition to check if the file has a matching header file in the same directory.
		if [[ ! $(find $file_directory -type f -name $headerfile) ]]; then
			compliance_fail_file "compliance_check_file_headercheck" $FILE "This file doesn't have a matching header"
		fi

	fi

	return 0
}

######################################## FUNCTION #################################################
###
### Name:		compliance_get_rules_headercheck
###
### Inputs/Outputs:	None.
###
### Purpose:		Prints out a summary of the code compliance rules for the headercheck test.
###
###################################################################################################

compliance_get_rules_headercheck()
{
	echo "Header file conventions:"
	echo "\tAll C++ anc C files should have a corresponding header file."
	echo ""
}

# ALL DONE.
