#!/bin/bash

SCRIPT=`readlink -f $0`
SCRIPTPATH=`dirname $SCRIPT`
TCPATH=$(echo $SCRIPTPATH | sed 's/\/bld.*//')
count=0
check=1


for FILE in $(find $TCPATH/* -name "*.cpp" -o -name "*.hpp" -o -name "*.c" -o -name "*.h" -o -name "*.pde"); do

	filename=$(basename "$FILE")
	echo "$filename"
	valcase='0-9a-z_.'
	path="${FILE%.*}"
	filename="${filename%.*}"
	headerfile=$filename".hpp"
	cppfile=$filename".cpp"

		if [[ "$filename" =~ [^$valcase] ]]; then
			count=$((count+1))
			check=0
			echo -e "\n------------------------------------------------------------------------------"
			echo "WARNING: Filename" $filename "contains special/UPPERCASE characters. Please change it."
			echo -e "------------------------------------------------------------------------------\n"
		fi
done

if [[ $check == 0 ]]; then
	echo -e "\n$count file(s) has special characters\n"
elif [[ $check == 1 ]]; then
	echo "All filenames are valid"
fi

#if [[ $filename =~ " "  ||  $filename =~ "!"  ||  $filename =~ "*"  ||  $filename =~ "|"  ||  $filename =~ "?"  ||  $filename =~ "["  ||  $filename =~ "]"  ||  		$filename =~ "!"  ||  $filename =~ "%"  ||  $filename =~ "\&"  ||  $filename =~ "?"  ||  $filename =~ "/"  ||  $filename =~ "\\"  ||  $filename =~ "$"  ||  			$filename =~ "'"  ||  $filename =~ "\""  ||  $filename =~ ";"  ||  $filename =~ "("  ||  $filename =~ ")"  ||  $filename =~ "^"  ||  $filename =~ ">"  ||  			$filename =~ "<"  ||  $filename =~ ":"  ||  $filename =~ "=" ||  $filename =~ "#" ]] ; then
