#!/bin/bash



################################################################################################################
#This script is for imposing Commenting conventions in all the files.
#It checks whether the file concludes with "// ALL DONE" comment. This is to ensure that the file is present in
#entirety and has not been accidentally truncated
#If the condition fails, a warning message is displayed.
################################################################################################################


# Determine what the absolute path to the root of the toolchain is.
SCRIPT=`readlink -f $0`
SCRIPTPATH=`dirname $SCRIPT`
TCPATH=$(echo $SCRIPTPATH | sed 's/\/bld.*//')

#This for loop is responsible for looping through all files with required file formats (.c, .cpp, .h, .hpp, .pde) in the ValleyForge directory
for FILE in $(find $TCPATH/ -name "*.cpp" -o -name "*.hpp" -o -name "*.c" -o -name "*.h" -o -name "*.pde"); do

string=$(tail -1 $FILE | head -1)
if [[ $string != "// ALL DONE." ]]; then
echo -e "\n------------------------------------------------------------------------------"
echo -e "\nWARNING: ALL DONE comment is missing at end of \"$FILE\". Please check if the file is complete. If complete, add \"// ALL DONE.\" to the last line of the file.\n"
echo -e "------------------------------------------------------------------------------\n"
fi

done

