#!/bin/bash


################################################################################################################
#This script is for imposing naming conventions in all the files.
#Each source file should have a matching header file of the same name with corresponding file extensions.
#It checks whether each file (C/C++) has a matching header file.
#If no matching header files are found, a warning message is displayed along with the file name.
################################################################################################################


# Determine what the absolute path to the root of the toolchain is.
SCRIPT=`readlink -f $0`
SCRIPTPATH=`dirname $SCRIPT`
TCPATH=$(echo $SCRIPTPATH | sed 's/\/bld.*//')

# Define the colours used for interface output.
source $TCPATH/bld/common/def_colours

echo -e "${GREEN}------------------------------------------------------------------------------${NO_COLOUR}"
echo -e "${BOLD_CYAN}Checking for matching headers for cpp files\n${NO_COLOUR}"
for FILE in $(find $TCPATH/ -name "*.cpp"); do
	filename=$(basename "$FILE")
	path="${FILE%.*}"
	temp=${path#/*}
	filename="${filename%.*}"
	headerfile=$filename".hpp"
	cppfile=$filename".cpp"
	#filename=$(echo "${FILE%%.*}")
	if [[ ! $(find $TCPATH -type f -name $headerfile) ]]; 
	then
		echo -e "${RED}Header file missing for ${CYAN}$FILE${NO_COLOUR}"
	fi
done
echo -e "\n${BOLD_CYAN}Done checking for matching headers for cpp files${NO_COLOUR}"
echo -e "${GREEN}------------------------------------------------------------------------------\n${NO_COLOUR}"
 
echo -e "${GREEN}------------------------------------------------------------------------------${NO_COLOUR}"
echo -e "${BOLD_CYAN}Checking for matching headers for c files\n${NO_COLOUR}"
for FILE in $(find $TCPATH/ -name "*.c"); do
	filename=$(basename "$FILE")
	path="${FILE%.*}"
	filename="${filename%.*}"
	headerfile=$filename".h"
	cppfile=$filename".c"
	#filename=$(echo "${FILE%%.*}")
	if [[ ! $(find $TCPATH -type f -name $headerfile) ]]; 
	then
		echo -e "${RED}Header file missing for ${CYAN}$FILE${NO_COLOUR}"
	fi
done
echo -e "\n${BOLD_CYAN}Done checking for matching headers for c files${NO_COLOUR}"
echo -e "${GREEN}------------------------------------------------------------------------------\n${NO_COLOUR}"

echo -e "${BOLD_WHITE}${UNDERLINED}FILE NAME CONVENTIONS:\n${NO_COLOUR}"
echo -e "${GREEN}Each source file should have a matching header file of the same name with a proper extension \nE.g. ${YELLOW}class.cpp should have a matching header file class.hpp; \nclass.c should have a matching header file class.h\n${NO_COLOUR}"  
