#!/bin/bash
count=0

# Determine what the absolute path to the root of the toolchain is.
SCRIPT=`readlink -f $0`
SCRIPTPATH=`dirname $SCRIPT`
TCPATH=$(echo $SCRIPTPATH | sed 's/\/bld.*//')

# Define the colours used for interface output.
source $TCPATH/bld/common/def_colours

for FILE in $(find $TCPATH/ -name "*.cpp" -o -name "*.hpp" -o -name "*.c" -o -name "*.h" -o -name "*.pde"); do
	count=$((count+1))
	uncrustify -c my.cfg -f $FILE -o $FILE
	sed -i ':r s:\(.*\)/[*]\(.*\)[*]/\(.*\):\1\3 //\2:;tr;s://\(.*\)//\(.*\)://\2\1:;tr' $FILE #latest working one
	#sed -i 's:\(.*\)/[*]\(.*\)[*]/:\1 // \2:' $FILE #used for replacing single line /*..*/ comments to //
	sed -i 's/todo[ -: ]*/ TODO - /I' $FILE #working one
	#sed -i 's/todo  / TODO -/I' $FILE #used for replacing case insensitive todo with TODO
	sed -i 's/note[ -: ]*/ NOTE - /I' $FILE #working one
	#sed -i 's/note/ NOTE -/I' $FILE #used for replacing case insensitive note with NOTE
done

echo -e "\n${YELLOW}$count ${GREEN}files have been modified according to layout and commenting conventions.${NO_COLOUR}\n"
