#!/bin/bash

###########################################################################################################################
#This script is responsible for reading inputs from the configuration file and running corresponding scripts.
#If the value for an option is set to true, then the suitable script is run.
#If the user provides an invalid value for an option, an error message is displayed.
#Likewise, if an invalid option is provided, an error message is displayed.
###########################################################################################################################


SCRIPT=`readlink -f $0`
SCRIPTPATH=`dirname $SCRIPT`
TCPATH=$(echo $SCRIPTPATH | sed 's/\/bld.*//')

# Define the colours used for interface output.
source $TCPATH/bld/common/def_colours

while read line
do
	name=$line

	if [[ $name =~ "=" ]]; then

		option=${name%=*}
		value=${name#*=}
		start=${value#*\'}
		end=${start%\'*}

		if [[ "$end" == "TRUE" || "$end" == "true" ]]; then

			case $option in

				(*variablename*) 
						bash $TCPATH/bld/code_compliance/varname > varnamelog.txt;;
				(*classstructname*) 
						bash $TCPATH/bld/code_compliance/classnamecheck > classnamecheck.txt ;;
				(*constname*) 
						bash $TCPATH/bld/code_compliance/constcheck > constcheck.txt;;
				(*funcname*) 
						bash $TCPATH/bld/code_compliance/funcnamecheck > funcnamecheck.txt;;
				(*filecomplete*) 
						bash $TCPATH/bld/code_compliance/filecomplete > filecomplete.txt;;
				(*headerguard*) 
						bash $TCPATH/bld/code_compliance/headerguard > headerguard.txt;;
				(*filename*) 
						bash $TCPATH/bld/code_compliance/filenamesplchar > filenamesplchar.txt;;
				(*filecheck*) 
						bash $TCPATH/bld/code_compliance/filecomplete > filecomplete.txt;;
				(*layout*) 
						bash $TCPATH/bld/code_compliance/layout > layout.txt;;
				*) 
						echo -e "${RED}Invalid option for value ${HIGHLIGHT_BLUE}$end${NO_COLOUR}" ;;

			esac
		elif [[ "$end" == "false" || "$end" == "FALSE" ]]; then
			:
		else
			echo "${RED}Invalid value for option ${HIGHLIGHT_BLUE}$option${NO_COLOUR}"
		fi
	fi
done < $1
