#!/bin/bash
count=0

# Determine what the absolute path to the root of the toolchain is.
SCRIPT=`readlink -f $0`
SCRIPTPATH=`dirname $SCRIPT`
TCPATH=$(echo $SCRIPTPATH | sed 's/\/bld.*//')
dir=$TCPATH/bld/code_compliance/config_files

# Define the colours used for interface output.
source $TCPATH/bld/common/def_colours

echo -e "${RED}LAYOUT CONVENTIONS ${CYAN}$1\n${NO_COLOUR}"

for FILE in $(find $1 -name "*.cpp" -o -name "*.hpp" -o -name "*.c" -o -name "*.h" -o -name "*.pde"); do

	count=$((count+1))
	uncrustify -c $dir/my.cfg -f $FILE -o $FILE

	#Check if the file contains any line breaks. If present, TODO - Find a way to change only the lines which do not contain line breaks. Else do the usual processing.
	if [[ $(cat $FILE | pcregrep -M '\\\n') ]]; then
		#echo "success"
		while read line
		do
			name=$line
			count1=$((count1+1))
			string=$(awk 'NR == '"$count1"' ' $FILE)
			if [[ $string =~ "\\" ]]; then
				:
			else
				echo "$string" | sed -i ''"$count1"'s:\(.*\)/[*]\(.*\)[*]/:\1 // \2:'
			fi
		done < $FILE
	#else
		#sed -i ':r s:\(.*\)/[*]\(.*\)[*]/\(.*\):\1\3 //\2:;tr;s://\(.*\)//\(.*\)://\2\1:;tr' $FILE
	fi
	#sed -i 's/todo[ -: ]*/ TODO - /I' $FILE #working one
	#sed -i 's/note[ -: ]*/ NOTE - /I' $FILE #working one

done

echo -e "\n${YELLOW}$count ${GREEN}files have been modified according to layout and commenting conventions.${NO_COLOUR}\n"
echo -e "${GREEN}--------------------------------------------------------------------------------${NO_COLOUR}"
echo -e "${GREEN}--------------------------------------------------------------------------------\n\n${NO_COLOUR}"



	#sed -i ':r s:\(.*\)/[*]\(.*\)[*]/\(.*\):\1\3 //\2:;tr;s://\(.*\)//\(.*\)://\2\1:;tr' $FILE #latest working one
	#sed -i 's:\(.*\)/[*]\(.*\)[*]/:\1 // \2:' $FILE #used for replacing single line /*..*/ comments to //
	#sed -i 's:(.*)/[*](.*)[*]/:\1 // \2:' $FILE #used for replacing single line /*..*/ comments to //
	#sed -i 's/todo  / TODO -/I' $FILE #used for replacing case insensitive todo with TODO
	#sed -i 's/note/ NOTE -/I' $FILE #used for replacing case insensitive note with NOTE
