#!/bin/bash
#count=0
#while read line#
#do
#name="/* Setup the correct byte alignment mask for the defined byte alignment. */"
#count=$((count+1))
#if [[ "$name" == /* && "$name" == */ ]]; then
#
#echo "$name" | sed -i ':r $counts:\(.*\)/[*]\(.*\)[*]/\(.*\):\1\3 //\2:;tr;s://\(.*\)//\(.*\)://\2\1:;tr' $1 #latest working one
#fi
#done < $1

SCRIPT=`readlink -f $0`
SCRIPTPATH=`dirname $SCRIPT`
TCPATH=$(echo $SCRIPTPATH | sed 's/\/bld.*//')

# Define the colours used for interface output.
source $TCPATH/bld/common/def_colours
dir=$TCPATH/bld/code_compliance
#cd $dir

bash $dir/varname | tee $dir/varnamelog.txt
