#!/bin/bash
echo "Enter a string:"
while read var; do
        echo ${var:0:1}
        case ${var:0:1} in
        [0-9]*)
                echo "$var begin with a digit."
                ;;
        [[:upper:]])
                echo "$var begin with a uppercase letter."
                ;;
        [[:lower:]])
                echo "$var begin with a lowercase letter."
                ;;
        *)
                echo "$var begin with another symbol."
                ;;
        esac
done

exit 0
