#!/bin/bash

SCRIPT=`readlink -f $0`
SCRIPTPATH=`dirname $SCRIPT`
TCPATH=$(echo $SCRIPTPATH | sed 's/\/bld.*//')
count=0;
for FILE in $(find $TCPATH/ -name "*.cpp"-o -name "*.hpp" -o -name "*.c" -o -name "*.h" -o -name "*.pde"); do
count=$((count+1))
filename=$(basename "$FILE")
path="${FILE%.*}"
filename="${filename%.*}"
headerfile=$filename".hpp"
cppfile=$filename".cpp"
if [[ $filename =~ " "  ||  $filename =~ "!"  ||  $filename =~ "*"  ||  $filename =~ "|"  ||  $filename =~ "?"  ||  $filename =~ "["  ||  $filename =~ "]"  ||  $filename =~ "!"  ||  $filename =~ "%"  ||  $filename =~ "&"  ||  $filename =~ "?"  ||  $filename =~ "/"  ||  $filename =~ "\\"  ||  $filename =~ "$"  ||  $filename =~ "'"  ||  $filename =~ "\""  ||  $filename =~ ";"  ||  $filename =~ "("  ||  $filename =~ ")"  ||  $filename =~ "^"  ||  $filename =~ ">"  ||  $filename =~ "<"  ||  $filename =~ ":"  ||  $filename =~ "=" ||  $filename =~ "#" ]] ; then
echo "Filename" $filename "contains special characters.. Please change"
else
echo "Filename:" $filename
fi
done
echo "count value is" $count
